# Import Librarie

In [1]:
import pandas as pd

In [2]:
# load dataset from file
df = pd.read_csv(r"C:\Users\puspa\OneDrive\Desktop\Job_Market_ Analysis\Job_Market_ Dataset_raw.csv")

In [3]:
# Display all columns and rows in the DataFrame
pd.set_option('display.max_rows',None)
pd.set_option('display.max_columns',None)

In [4]:
# display rows to understand data
df.head(101)

,ID,Job_Title,Salary_Estimate,FIELD4,Rating,Company_Name,Location,Headquarters,Size,Founded,Type_of_ownership,Industry,Sector,Revenue,Competitors,Hourly,Employer_provided,Lower_Salary,Upper_Salary,Avg_SalaryK,company_txt,Job_Location,Age,Python,spark,aws,excel,sql_,sas,keras,pytorch,scikit,tensor,hadoop,tableau,bi,flink,mongo,google_an,job_title_sim,seniority_by_title,Degree
0,0,Data Scientist,$53K-$91K (Glassdoor est.),NaN,3.8,Tecolote Research\n3.8,"Albuquerque, NM","Goleta, CA",501 - 1000,1973,Company - Private,Aerospace & Defense,Aerospace & Defense,$50 to $100 million (USD),-1,0,0,53,91,72.0,Tecolote Research,NM,48,1,0,0,1,0,1,0,0,0,0,0,1,1,0,0,0,data scientist,na,M
1,1,Healthcare Data Scientist,$63K-$112K (Glassdoor est.),NaN,3.4,University of Maryland Medical System\n3.4,"Linthicum, MD","Baltimore, MD",10000+,1984,Other Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1,0,0,63,112,87.5,University of Maryland Medical System,MD,37,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,data scientist,na,M
2,2,Data Scientist,$80K-$90K (Glassdoor est.),NaN,4.8,KnowBe4\n4.8,"Clearwater, FL","Clearwater, FL",501 - 1000,2010,Company - Private,Security Services,Business Services,$100 to $500 million (USD),-1,0,0,80,90,85.0,KnowBe4,FL,11,1,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,data scientist,na,M
3,3,Data Scientist,$56K-$97K (Glassdoor est.),NaN,3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 - 5000,1965,Government,Energy,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa...",0,0,56,97,76.5,PNNL,WA,56,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,data scientist,na,na
4,4,Data Scientist,$86K-$143K (Glassdoor est.),NaN,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 - 200,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee",0,0,86,143,114.5,Affinity Solutions,NY,23,1,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,data scientist,na,na
5,5,Data Scientist,$71K-$119K (Glassdoor est.),NaN,3.4,CyrusOne\n3.4,"Dallas, TX","Dallas, TX",201 - 500,2000,Company - Public,Real Estate,Real Estate,$1 to $2 billion (USD),"Digital Realty, CoreSite, Equinix",0,0,71,119,95.0,CyrusOne,TX,21,1,0,1,1,1,0,0,0,0,0,0,0,1,0,1,0,data scientist,na,na
6,6,Data Scientist,$54K-$93K (Glassdoor est.),NaN,4.1,ClearOne Advantage\n4.1,"Baltimore, MD","Baltimore, MD",501 - 1000,2008,Company - Private,Banks & Credit Unions,Finance,Unknown / Non-Applicable,-1,0,0,54,93,73.5,ClearOne Advantage,MD,13,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,data scientist,na,na
7,7,Data Scientist,$86K-$142K (Glassdoor est.),NaN,3.8,Logic20/20\n3.8,"San Jose, CA","Seattle, WA",201 - 500,2005,Company - Private,Consulting,Business Services,$25 to $50 million (USD),-1,0,0,86,142,114.0,Logic20/20,CA,16,1,1,1,1,1,0,0,1,0,1,0,0,0,0,0,0,data scientist,na,M
8,8,Research Scientist,$38K-$84K (Glassdoor est.),NaN,3.3,Rochester Regional Health\n3.3,"Rochester, NY","Rochester, NY",10000+,2014,Hospital,Health Care Services & Hospitals,Health Care,$500 million to $1 billion (USD),-1,0,0,38,84,61.0,Rochester Regional Health,NY,7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,other scientist,na,P
9,9,Data Scientist,$120K-$160K (Glassdoor est.),NaN,4.6,<intent>\n4.6,"New York, NY","New York, NY",51 - 200,2009,Company - Private,Internet,Information Technology,$100 to $500 million (USD),"Clicktripz, SmarterTravel",0,0,120,160,140.0,<intent>,NY,12,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,data scientist,na,na
10,10,Data Scientist,$126K-$201K (Glassdoor est.),NaN,3.5,Wish\n3.5,"San Jose, CA","San Francisco, CA",501 - 1000,2011,Company - Private,Other Retail Stores,Retail,$1 to $2 billion (USD),-1,0,0,126,201,163.5,Wish,CA,10,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,data scientist,na,na
11,11,Data Scientist,$64K-$106K (Glassdoor est.),NaN,4.1,ManTech\n4.1,"Chantilly, VA","Herndon, VA",5001 - 10000,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1,0,0,64,106,85.0,ManTech,VA,53,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,data scientist,na,na
12,12,Staff Data Scientist - Technology,$106K-$172K (Glassdoor est.),NaN,3.2,Walmart\n3.2,"Plano, TX","Bentonville, AR",10000+,1962,Company - Public,"Department, Clothing, & Shoe Stores",Retail,$10+ billion (USD),"Target, Costco Wholesale, Amazon",0,0,106,172,139.0,Walmart,TX,59,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,data scientist,na,M
13,13,Data Analyst,$46K-$85K (Glassdoor est.),NaN,4.1,Yesler\n4.1,"Seattle, WA","Seattle, WA",201 - 500,2012,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,-1,0,0,46,85,65.5,Yesler,WA,9,1,1,1,1,1,0,0,0,0,0,0,1,1,0,0,0,analyst,na,na
14,14,Data Scientist,$83K-$144K (Glassdoor est.),NaN,3.7,Takeda Pharmaceuticals\n3.7,"Cambridge, MA","OSAKA, Japan",10000+,1781,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),"Novartis, Baxter, Pfizer",0,0,83,144,113.5,Takeda Pharmaceuticals,MA,240,1,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,data scientist,na,M
15,15,Data Engineer I,$102K-$190K (Glassdoor est.),NaN,3.6,Audible\n3.6,"Newark, NJ","Newark, NJ",1001 - 5000,1995,Subsidiary or Business Segment,Motion Picture Production & Distribution,Media,Unknown / Non-Applicable,-1,0,0,102,190,146.0,Audible,NJ,26,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,data engineer,na,na
16,16,"Scientist I/II, Biology",$67K-$137K (Glassdoor est.),NaN,3.9,Blueprint Medicines\n3.9,"Cambridge, MA","Cambridge, MA",51 - 200,2011,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$1 to $5 million (USD),"bluebird bio, Agios Pharmaceuticals, Celgene",0,0,67,137,102.0,Blueprint Medicines,MA,10,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,other scientist,na,P
17,17,Customer Data Scientist,$118K-$189K (Glassdoor est.),NaN,4.3,h2o.ai\n4.3,"Mountain View, CA","Mountain View, CA",201 - 500,2011,Company - Private,Enterprise Software & Network Solutions,Information Technology,Unknown / Non-Applicable,-1,0,0,118,189,153.5,h2o.ai,CA,10,1,1,1,1,0,0,0,0,0,0,1,0,0,0,0,0,data scientist,na,M
18,18,Data Scientist - Health Data Analytics,$110K-$175K (Glassdoor est.),NaN,4.2,Nuna\n4.2,"San Francisco, CA","San Francisco, CA",51 - 200,2010,Company - Private,Enterprise Software & Network Solutions,Information Technology,Unknown / Non-Applicable,-1,0,0,110,175,142.5,Nuna,CA,11,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,data scientist,na,na
19,19,Data Scientist,$64K-$111K (Glassdoor est.),NaN,4.0,Pinnacol Assurance\n4.0,"Denver, CO","Denver, CO",501 - 1000,1915,Nonprofit Organization,Insurance Carriers,Insurance,$500 million to $1 billion (USD),-1,0,0,64,111,87.5,Pinnacol Assurance,CO,106,1,0,0,1,1,0,1,1,1,1,0,0,0,0,0,0,data scientist,na,M
20,20,Data Scientist,$81K-$130K (Glassdoor est.),NaN,3.2,Porch\n3.2,"Seattle, WA","Seattle, WA",201 - 500,2012,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,"Angie's List, HomeAdvisor, Thumbtack",0,0,81,130,105.5,Porch,WA,9,1,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,data scientist,na,M
21,21,Senior Data Scientist / Machine Learning,$73K-$119K (Glassdoor est.),NaN,3.9,Health IQ\n3.9,"Dallas, TX","Mountain View, CA",201 - 500,2013,Company - Private,Insurance Agencies & Brokerages,Insurance,Unknown / Non-Applicable,-1,0,0,73,119,96.0,Health IQ,TX,8,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,data scientist,sr,P
22,22,Data Scientist - Quantitative,$86K-$139K (Glassdoor est.),NaN,3.8,Truckstop.com\n3.8,"Chicago, IL","New Plymouth, ID",501 - 1000,1995,Company - Private,Logistics & Supply Chain,Transportation & Logistics,Unknown / Non-Applicable,-1,0,0,86,139,112.5,Truckstop.com,IL,26,1,0,1,1,1,0,0,0,0,0,0,0,0,0,1,0,data scientist,na,M
23,23,Data Scientist,$63K-$105K (Glassdoor est.),NaN,4.3,SMC 3\n4.3,"Louisville, KY","Peachtree City, GA",51 - 200,1935,Nonprofit Organization,Logistics & Supply Chain,Transportation & Logistics,$10 to $25 million (USD),-1,0,0,63,105,84.0,SMC 3,KY,86,1,0,0,1,1,0,0,0,0,0,0,1,0,0,0,0,data scientist,na,M
24,25,Data Scientist,$109K-$177K (Glassdoor est.),NaN,4.0,Novetta\n4.0,"Herndon, VA","Mc Lean, VA",501 - 1000,2012,Company - Private,Enterprise Software & Network Solutions,Information Technology,$100 to $500 million (USD),"Leidos, CACI International, Booz Allen Hamilton",0,0,109,177,143.0,Novetta,VA,9,1,0,1,0,0,0,1,0,0,1,0,0,0,0,0,0,data scientist,na,na
25,26,Digital Health Data Scientist,$63K-$110K (Glassdoor est.),NaN,4.0,Pfizer\n4.0,"Cambridge, MA","New York, NY",10000+,1849,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),-1,0,0,63,110,86.5,Pfizer,MA,172,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,data scientist,na,na
26,27,Data Scientist,$75K-$124K (Glassdoor est.),NaN,3.5,First Tech Federal Credit Union\n3.5,"Hillsboro, OR","San Jose, CA",1001 - 5000,1952,Company - Private,Banks & Credit Unions,Finance,$100 to $500 million (USD),-1,0,0,75,124,99.5,First Tech Federal Credit Union,OR,69,1,1,1,1,1,0,1,0,1,1,0,1,0,0,0,0,data scientist,na,na
27,28,Associate Data Analyst,$34K-$61K (Glassdoor est.),NaN,3.7,The Hanover Insurance Group\n3.7,"Worcester, MA","Worcester, MA",5001 - 10000,1852,Company - Public,Insurance Carriers,Insurance,$5 to $10 billion (USD),-1,0,0,34,61,47.5,The Hanover Insurance Group,MA,169,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,analyst,na,na
28,29,Clinical Data Scientist,$63K-$105K (Glassdoor est.),NaN,4.0,Pfizer\n4.0,"Groton, CT","New York, NY",10000+,1849,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),-1,0,0,63,105,84.0,Pfizer,CT,172,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,data scientist,na,M
29,30,Data Scientist,$80K-$90K (Glassdoor est.),NaN,4.8,KnowBe4\n4.8,"Clearwater, FL","Clearwater, FL",501 - 1000,2010,Company - Private,Security Services,Business Services,$100 to $500 million (USD),-1,0,0,80,90,85.0,KnowBe4,FL,11,1,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,data scientist,na,M
30,31,Data Scientist,$56K-$97K (Glassdoor est.),NaN,3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 - 5000,1965,Government,Energy,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa...",0,0,56,97,76.5,PNNL,WA,56,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,data scientist,na,na
31,32,Data Scientist,$72K-$120K (Glassdoor est.),NaN,3.6,Amrock\n3.6,"Detroit, MI","Detroit, MI",1001 - 5000,1997,Company - Private,Real Estate,Real Estate,$500 million to $1 billion (USD),-1,0,0,72,120,96.0,Amrock,MI,24,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,data scientist,na,M
32,33,Data Scientist / Machine Learning Expert,$86K-$143K (Glassdoor est.),NaN,3.8,Novartis\n3.8,"Cambridge, MA","Basel, Switzerland",10000+,1996,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),-1,0,0,86,143,114.5,Novartis,MA,25,1,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,data scientist,na,na
33,34,Data Scientist,$93K-$149K (Glassdoor est.),NaN,3.8,Juniper Networks\n3.8,"Sunnyvale, CA","Sunnyvale, CA",5001 - 10000,1996,Company - Public,Telecommunications Services,Telecommunications,$2 to $5 billion (USD),-1,0,0,93,149,121.0,Juniper Networks,CA,25,1,1,0,1,1,0,1,0,1,1,0,0,0,0,1,0,data scientist,na,M
34,35,Data Scientist,$85K-$140K (Glassdoor est.),NaN,4.7,New England Biolabs\n4.7,"Ipswich, MA","Ipswich, MA",201 - 500,1974,Company - Private,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable,"Thermo Fisher Scientific, Enzymatics, Illumina",0,0,85,140,112.5,New England Biolabs,MA,47,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,data scientist,na,na
35,36,Web Data Analyst,$77K-$135K (Glassdoor est.),NaN,4.2,Clarity Insights\n4.2,"San Jose, CA","Chicago, IL",201 - 500,2008,Company - Private,IT Services,Information Technology,Unknown / Non-Applicable,-1,0,0,77,135,106.0,Clarity Insights,CA,13,1,0,0,1,1,0,0,0,0,0,0,1,1,0,0,0,analyst,na,na
36,37,Data Scientist,$82K-$132K (Glassdoor est.),NaN,3.5,Esri\n3.5,"Redlands, CA","Redlands, CA",1001 - 5000,1969,Company - Private,Computer Hardware & Software,Information Technology,$1 to $2 billion (USD),Pitney Bowes,0,0,82,132,107.0,Esri,CA,52,1,1,1,0,0,0,0,0,0,0,1,1,0,0,1,0,data scientist,na,M
37,38,Data Scientist,$83K-$137K (Glassdoor est.),NaN,4.7,Systems & Technology Research\n4.7,"Woburn, MA","Woburn, MA",201 - 500,2010,Company - Private,Aerospace & Defense,Aerospace & Defense,$100 to $500 million (USD),-1,0,0,83,137,110.0,Systems & Technology Research,MA,11,1,1,0,1,1,0,0,1,1,1,1,0,0,0,0,0,data scientist,na,P
38,39,Senior Data Scientist,$115K-$180K (Glassdoor est.),NaN,3.5,Sartorius\n3.5,"Fremont, CA","Gottingen, Germany",5001 - 10000,1870,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$1 to $2 billion (USD),-1,0,0,115,180,147.5,Sartorius,CA,151,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,data scientist,sr,M
39,40,Data Engineer,$74K-$138K (Glassdoor est.),NaN,3.5,Lancer Insurance\n3.5,"Long Beach, NY","Long Beach, NY",201 - 500,1985,Company - Private,Insurance Carriers,Insurance,$100 to $500 million (USD),-1,0,0,74,138,106.0,Lancer Insurance,NY,36,1,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,data engineer,na,M
40,41,Data Analyst,$64K-$112K (Glassdoor est.),NaN,4.2,Sauce Labs\n4.2,"San Francisco, CA","San Francisco, CA",201 - 500,2008,Company - Private,IT Services,Information Technology,$50 to $100 million (USD),"BrowserStack, Selenium Master, Perfecto Mobile",0,0,64,112,88.0,Sauce Labs,CA,13,1,0,1,1,1,0,0,0,0,0,0,1,0,0,1,0,analyst,na,na
41,43,Data Engineer,$68K-$129K (Glassdoor est.),NaN,3.6,Persivia\n3.6,"Marlborough, MA","Lowell, MA",Jan-50,-1,Company - Private,-1,-1,Less than $1 million (USD),-1,0,0,68,129,98.5,Persivia,MA,-1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,data engineer,na,na
42,44,Data Scientist - Algorithms & Inference,$110K-$175K (Glassdoor est.),NaN,4.2,Nuna\n4.2,"San Francisco, CA","San Francisco, CA",51 - 200,2010,Company - Private,Enterprise Software & Network Solutions,Information Technology,Unknown / Non-Applicable,-1,0,0,110,175,142.5,Nuna,CA,11,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,data scientist,na,M
43,45,Scientist,$52K-$113K (Glassdoor est.),NaN,3.4,Edgewell Personal Care\n3.4,"Allendale, NJ","Shelton, CT",5001 - 10000,2015,Company - Public,Consumer Products Manufacturing,Manufacturing,$2 to $5 billion (USD),"Unilever, Procter & Gamble, Henkel",0,0,52,113,82.5,Edgewell Personal Care,NJ,6,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,other scientist,na,M
44,46,Senior Data Scientist,$110K-$150K(Employer est.),NaN,4.3,Equity Residential\n4.3,"Chicago, IL","Chicago, IL",1001 - 5000,1993,Company - Public,Real Estate,Real Estate,$2 to $5 billion (USD),"UDR, AvalonBay Communities, Essex Property Trust",0,0,110,150,130.0,Equity Residential,IL,28,1,1,0,1,1,0,0,0,1,0,1,1,1,0,0,0,data scientist,sr,M
45,48,Data Scientist,Employer Provided Salary:$150K-$160K,NaN,5.0,BPA Services\n5.0,"Washington, DC","Alexandria, VA",unknown,-1,Company - Private,Enterprise Software & Network Solutions,Information Technology,Unknown / Non-Applicable,-1,0,1,150,160,155.0,BPA Services,DC,-1,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,data scientist,na,na
46,49,Lead Data Scientist,$158K-$211K (Glassdoor est.),NaN,3.7,Visa Inc.\n3.7,"Bellevue, WA","Foster City, CA",10000+,1958,Company - Public,IT Services,Information Technology,$10+ billion (USD),"American Express, Mastercard, Discover",0,0,158,211,184.5,Visa Inc.,WA,63,1,0,0,1,1,1,0,0,0,0,0,1,0,0,0,0,data scientist,sr,na
47,50,Associate Data Analyst,$20K-$39K (Glassdoor est.),NaN,3.1,Intrado\n3.1,"Longmont, CO","Omaha, NE",5001 - 10000,1986,Company - Private,Enterprise Software & Network Solutions,Information Technology,$2 to $5 billion (USD),-1,0,0,20,39,29.5,Intrado,CO,35,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,analyst,na,M
48,51,Spectral Scientist/Engineer,$56K-$117K (Glassdoor est.),NaN,4.7,Centauri\n4.7,"Beavercreek, OH","Chantilly, VA",501 - 1000,1999,Company - Private,Aerospace & Defense,Aerospace & Defense,$100 to $500 million (USD),"TASC, Vencore, Booz Allen Hamilton",0,0,56,117,86.5,Centauri,OH,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,other scientist,na,M
49,52,College Hire - Data Scientist - Open to Decemb...,$63K-$99K (Glassdoor est.),NaN,3.7,Caterpillar\n3.7,"Peoria, IL","Deerfield, IL",10000+,1925,Company - Public,Industrial Manufacturing,Manufacturing,$10+ billion (USD),"John Deere, Komatsu, CNH Industrial",0,0,63,99,81.0,Caterpillar,IL,96,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,data scientist,na,na
50,54,Data Scientist,$68K-$114K (Glassdoor est.),NaN,3.8,Zimmerman Advertising\n3.8,"Fort Lauderdale, FL","Fort Lauderdale, FL",501 - 1000,1984,Subsidiary or Business Segment,Advertising & Marketing,Business Services,Unknown / Non-Applicable,-1,0,0,68,114,91.0,Zimmerman Advertising,FL,37,1,0,0,1,1,0,0,0,0,0,1,1,0,0,0,0,data scientist,na,na
51,55,"Data Scientist, Office of Data Science",$86K-$143K (Glassdoor est.),NaN,3.3,Liberty Mutual Insurance\n3.3,"Boston, MA","Boston, MA",10000+,1912,Company - Private,Insurance Carriers,Insurance,$10+ billion (USD),"Travelers, Allstate, State Farm",0,0,86,143,114.5,Liberty Mutual Insurance,MA,109,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,data scientist,na,na
52,56,Data Science Analyst,$41K-$95K (Glassdoor est.),NaN,4.6,"Torch Technologies, Inc.\n4.6","Huntsville, AL","Huntsville, AL",1001 - 5000,2002,Company - Private,Aerospace & Defense,Aerospace & Defense,$100 to $500 million (USD),-1,0,0,41,95,68.0,"Torch Technologies, Inc.",AL,19,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,data scientist,na,na
53,57,Data Scientist,$86K-$144K (Glassdoor est.),NaN,3.7,Swiss Re\n3.7,"Armonk, NY","Zurich, Switzerland",10000+,1863,Company - Public,Insurance Agencies & Brokerages,Insurance,$10+ billion (USD),"Munich Re, Hannover RE, SCOR",0,0,86,144,115.0,Swiss Re,NY,158,1,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,data scientist,na,M
54,58,Data Scientist,$80K-$139K (Glassdoor est.),NaN,3.7,Northrop Grumman\n3.7,"San Diego, CA","Falls Church, VA",10000+,1939,Company - Public,Aerospace & Defense,Aerospace & Defense,$10+ billion (USD),-1,0,0,80,139,109.5,Northrop Grumman,CA,82,0,0,0,1,1,0,0,0,0,0,0,1,0,0,0,0,data scientist,na,na
55,59,Data Scientist,$56K-$95K (Glassdoor est.),NaN,3.5,Sartorius\n3.5,"Albuquerque, NM","Gottingen, Germany",5001 - 10000,1870,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$1 to $2 billion (USD),-1,0,0,56,95,75.5,Sartorius,NM,151,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,data scientist,na,M
56,60,Data Scientist,$120K-$189K (Glassdoor est.),NaN,4.1,Netskope\n4.1,"San Francisco, CA","Santa Clara, CA",501 - 1000,2012,Company - Private,Enterprise Software & Network Solutions,Information Technology,Unknown / Non-Applicable,"Skyhigh Networks, Zscaler, NortonLifeLock",0,0,120,189,154.5,Netskope,CA,9,1,1,0,1,0,0,0,0,0,1,0,0,0,1,0,0,data scientist,na,P
57,61,Data Scientist,$111K-$176K (Glassdoor est.),NaN,4.7,1904labs\n4.7,"Saint Louis, MO","Saint Louis, MO",51 - 200,2016,Company - Private,IT Services,Information Technology,Unknown / Non-Applicable,"Slalom, Daugherty Business Solutions",0,0,111,176,143.5,1904labs,MO,5,1,1,0,0,1,0,1,0,1,1,0,0,0,0,0,0,data scientist,na,na
58,62,Data Scientist,$54K-$93K (Glassdoor est.),NaN,4.1,ClearOne Advantage\n4.1,"Baltimore, MD","Baltimore, MD",501 - 1000,2008,Company - Private,Banks & Credit Unions,Finance,Unknown / Non-Applicable,-1,0,0,54,93,73.5,ClearOne Advantage,MD,13,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,data scientist,na,na
59,63,Data Scientist,$71K-$119K (Glassdoor est.),NaN,3.4,CyrusOne\n3.4,"Dallas, TX","Dallas, TX",201 - 500,2000,Company - Public,Real Estate,Real Estate,$1 to $2 billion (USD),"Digital Realty, CoreSite, Equinix",0,0,71,119,95.0,CyrusOne,TX,21,1,0,1,1,1,0,0,0,0,0,0,0,1,0,1,0,data scientist,na,na
60,65,Senior Data Scientist,$82K-$132K (Glassdoor est.),NaN,4.4,The David J. Joseph Company\n4.4,"Cincinnati, OH","Cincinnati, OH",201 - 500,1885,Subsidiary or Business Segment,Metals Brokers,Mining & Metals,Unknown / Non-Applicable,-1,0,0,82,132,107.0,The David J. Joseph Company,OH,136,1,0,1,0,1,0,0,0,0,0,0,1,1,0,0,0,data scientist,sr,M
61,66,Data Scientist,$84K-$146K (Glassdoor est.),NaN,4.3,USEReady\n4.3,"New York, NY","New York, NY",201 - 500,2011,Company - Private,Consulting,Business Services,$10 to $25 million (USD),-1,0,0,84,146,115.0,USEReady,NY,10,1,1,1,0,1,0,0,0,0,0,1,1,0,0,0,0,data scientist,na,na

In [5]:
# check datatype, null values, column info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 742 entries, 0 to 741
Data columns (total 42 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID                  742 non-null    int64
 1   Job_Title           742 non-null    object
 2   Salary_Estimate     742 non-null    object
 3   FIELD4              0 non-null      float64
 4   Rating              742 non-null    float64
 5   Company_Name        742 non-null    object
 6   Location            742 non-null    object
 7   Headquarters        742 non-null    object
 8   Size                742 non-null    object
 9   Founded             742 non-null    int64
 10  Type_of_ownership   742 non-null    object
 11  Industry            742 non-null    object
 12  Sector              742 non-null    object
 13  Revenue             742 non-null    object
 14  Competitors         742 non-null    object
 15  Hourly              742 non-null    int64
 16  Employer_provided   742 non-null    int64
 17  Lower_Salary        742 non-null    int64
 18  Upper_Salary        742 non-null    int64
 19  Avg_SalaryK         742 non-null    float64
 20  company_txt         742 non-null    object
 21  Job_Location        742 non-null    object
 22  Age                 742 non-null    int64
 23  Python              742 non-null    int64
 24  spark               742 non-null    int64
 25  aws                 742 non-null    int64
 26  excel               742 non-null    int64
 27  sql_                742 non-null    int64
 28  sas                 742 non-null    int64
 29  keras               742 non-null    int64
 30  pytorch             742 non-null    int64
 31  scikit              742 non-null    int64
 32  tensor              742 non-null    int64
 33  hadoop              742 non-null    int64
 34  tableau             742 non-null    int64
 35  bi                  742 non-null    int64
 36  flink               742 non-null    int64
 37  mongo               742 non-null    int64
 38  google_an           742 non-null    int64
 39  job_title_sim       742 non-null    object
 40  seniority_by_title  742 non-null    object
 41  Degree              742 non-null    object
dtypes: float64(3), int64(23), object(16)
memory usage: 243.6+ KB

In [6]:
# check missing values in each column
df.isnull().sum()

ID                      0
Job_Title               0
Salary_Estimate         0
FIELD4                742
Rating                  0
Company_Name            0
Location                0
Headquarters            0
Size                    0
Founded                 0
Type_of_ownership       0
Industry                0
Sector                  0
Revenue                 0
Competitors             0
Hourly                  0
Employer_provided       0
Lower_Salary            0
Upper_Salary            0
Avg_SalaryK             0
company_txt             0
Job_Location            0
Age                     0
Python                  0
spark                   0
aws                     0
excel                   0
sql_                    0
sas                     0
keras                   0
pytorch                 0
scikit                  0
tensor                  0
hadoop                  0
tableau                 0
bi                      0
flink                   0
mongo                   0
google_an               0
job_title_sim           0
seniority_by_title      0
Degree                  0
dtype: int64

In [7]:
# Remove unnecessary columns 'ID' and 'FIELD4'
df.drop(['ID', 'FIELD4'], axis=1, inplace=True)

In [8]:
# Count the number of each job title
df['Job_Title'].value_counts()

Job_Title
Data Scientist                                                                                        131
Data Engineer                                                                                          53
Senior Data Scientist                                                                                  34
Data Analyst                                                                                           15
Senior Data Engineer                                                                                   14
Senior Data Analyst                                                                                    12
Lead Data Scientist                                                                                     8
Marketing Data Analyst                                                                                  6
Sr. Data Engineer                                                                                       6
Machine Learning Engineer                                                                               5
Principal Data Scientist                                                                                5
R&D Specialist/ Food Scientist                                                                          4
Medical Laboratory Scientist                                                                            4
Research Scientist                                                                                      4
Senior Research Scientist-Machine Learning                                                              4
MED TECH/LAB SCIENTIST- SOUTH COASTAL LAB                                                               4
Analytics Manager - Data Mart                                                                           4
Food Scientist - Developer                                                                              4
Staff Scientist-Downstream Process Development                                                          4
Sr. Data Engineer - Contract-to-Hire (Java)                                                             4
Sr. Scientist Method Development                                                                        3
Project Scientist - Auton Lab, Robotics Institute                                                       3
Scientist, Molecular/Cellular Biologist                                                                 3
Associate Scientist, LC/MS Biologics                                                                    3
Revenue Analytics Manager                                                                               3
IT - Data Engineer II                                                                                   3
Research Scientist, Immunology - Cancer Biology                                                         3
Scientist - Biomarker and Flow Cytometry                                                                3
Senior Scientist - Regulatory Submissions                                                               3
ENVIRONMENTAL ENGINEER/SCIENTIST                                                                        3
Senior Data Science Systems Engineer                                                                    3
Senior Insurance Data Scientist                                                                         3
Associate Data Analyst- Graduate Development Program                                                    3
Scientist - Analytical Services                                                                         3
Principal Scientist, Chemistry & Immunology                                                             3
Director II, Data Science - GRM Actuarial                                                               3
Scientist/Senior Scientist, Autoimmune                                                                  3
Clinical Data Analyst                                                                                   3
Staff Data Engineer                                                                                     3
Consultant - Analytics Consulting                                                                       3
Lead Data Engineer                                                                                      3
Principal Scientist, Hematology                                                                         3
Staff Machine Learning Engineer                                                                         3
Software Engineer - Data Visualization                                                                  3
Senior Data Scientist - R&D Oncology                                                                    3
Principal Data Scientist (Computational Chemistry)                                                      3
Senior Scientist (Neuroscience)                                                                         3
Machine Learning Engineer - Regulatory                                                                  3
Scientist, Bacteriology                                                                                 3
Associate Director, Platform and DevOps- Data Engineering and Aritifical Intelligence                   3
Clinical Laboratory Scientist                                                                           3
Information Security Data Analyst                                                                       3
Sr. Data Analyst                                                                                        3
Data Science Manager                                                                                    3
Scientist                                                                                               3
Staff Scientist- Upstream PD                                                                            2
Sr Expert Data Science, Advanced Visual Analytics (Associate level)                                     2
Sr Data Analyst - IT                                                                                    2
Associate Machine Learning Engineer / Data Scientist May 2020 Undergrad                                 2
Senior Scientist - Biostatistician                                                                      2
Senior Data Scientist Oncology                                                                          2
Associate Principal Scientist, Pharmacogenomics                                                         2
Data Scientist - Systems Engineering                                                                    2
Data Engineer - Consultant (Charlotte Based)                                                            2
Data Analyst 1, full-time contract worker for up to 12 months                                           2
Scientist, Immuno-Oncology                                                                              2
Products Data Analyst II                                                                                2
Lead Data Analyst                                                                                       2
Data Science Engineer - Mobile                                                                          2
IT Associate Data Analyst                                                                               2
Scientist, Pharmacometrics                                                                              2
Business Data Analyst                                                                                   2
Principal, Data Science - Advanced Analytics                                                            2
Data Science Project Manager                                                                            2
Sr Scientist, Immuno-Oncology - Oncology                                                                2
Data Analytics Project Manager                                                                          2
Scientist Manufacturing - Kentucky BioProcessing                                                        2
Director - Data, Privacy and AI Governance                                                              2
Staff BI and Data Engineer                                                                              2
Associate Data Engineer                                                                                 2
Research Scientist – Security and Privacy                                                               2
Market Data Analyst                                                                                     2
Product Engineer – Data Science                                                                         2
Computational Chemist/Data Scientist                                                                    2
Director Data Science                                                                                   2
Senior Research Analytical Scientist-Non-Targeted Analysis                                              2
Systems Engineer II - Data Analyst                                                                      2
Product Engineer – Spatial Data Science and Statistical Analysis                                        2
Managing Data Scientist/ML Engineer                                                                     2
Technology-Minded, Data Professional Opportunities                                                      2
Salesforce Analytics Consultant                                                                         2
Scientist Manufacturing Pharma - Kentucky BioProcessing                                                 2
Sr Data Engineer (Sr BI Developer)                                                                      2
Associate, Data Science, Internal Audit                                                                 2
Associate Environmental Scientist - Wildlife Biologist                                                  2
Data Modeler - Data Solutions Engineer                                                                  2
Marketing Data Analyst, May 2020 Undergrad                                                              2
Corporate Risk Data Analyst (sql_ Based) - Milwaukee or                                                 2
Senior Manager, Epidemiologic Data Scientist                                                            2
Enterprise Architect, Data                                                                              2
Lead Big Data Engineer                                                                                  2
Sr Software Engineer (Data Scientist)                                                                   2
Senior Scientist - Toxicologist - Product Integrity (Stewardship)                                       2
Sr. Data Engineer (ETL Developer)                                                                       2
Senior Data Scientist Artificial Intelligence                                                           2
Analytics - Business Assurance Data Analyst                                                             2
Associate Director/Director, Safety Scientist                                                           2
Senior Scientist, Cell Pharmacology/Assay Development                                                   2
Data Analyst Senior                                                                                     2
Lead Data Engineer (Python)                                                                             2
Senior Data Scientist 4 Artificial Intelligence                                                         2
Medical Lab Scientist - MLT                                                                             2
Senior Operations Data Analyst, Call Center Operations                                                  2
Director II, Data Science - GRS Predictive Analytics                                                    2
RESEARCH COMPUTER SCIENTIST - RESEARCH ENGINEER - SR. COMPUTER SCIENTIST - SOFTWARE DEVELOPMENT         2
Geospatial Software Developer and Data Scientist                                                        2
Senior LiDAR Data Scientist                                                                             2
Big Data Engineer                                                                                       2
Medical Lab Scientist                                                                                   2
Senior Data & Machine Learning Scientist                                                                2
Radar Data Analyst                                                                                      2
VP, Data Science                                                                                        2
Machine Learning Research Scientist                                                                     2
Excel / VBA / sql_ Data Analyst                                                                         2
Sr. Data Scientist II                                                                                   2
Sr. Scientist, Quantitative Translational Sciences                                                      2
MED TECH/LAB SCIENTIST - LABORATORY                                                                     2
Principal Data Scientist with over 10 years experience                                                  2
Principal Scientist - Immunologist                                                                      2
Sr. Scientist - Digital & Image Analysis/Computational Pathology                                        2
Digital Marketing & ECommerce Data Analyst                                                              2
Analytics Manager                                                                                       2
Scientist, Analytical Development                                                                       2
Risk and Analytics IT, Data Scientist                                                                   2
Senior Scientist - Neuroscience                                                                         2
Data Engineer 5 - Contract (Remote)                                                                     2
Staff Data Scientist                                                                                    2
Data Scientist (Actuary, FSA or ASA)                                                                    2
Pricipal Scientist Molecular and cellular biologist                                                     2
Sr. Data Scientist - Analytics, Personalized Healthcare (PHC)                                           2
BI & Platform Analytics Manager                                                                         2
PL Actuarial-Lead Data Scientist                                                                        2
PV Scientist                                                                                            2
Data Scientist - Algorithms & Inference                                                                 2
Data Scientist - Quantitative                                                                           2
Data Scientist, Office of Data Science                                                                  2
College Hire - Data Scientist - Open to December 2019 Graduates                                         2
Senior Risk Data Scientist                                                                              2
Staff Data Scientist - Technology                                                                       2
Data Scientist / Machine Learning Expert                                                                2
Clinical Data Scientist                                                                                 2
Associate Data Analyst                                                                                  2
Digital Health Data Scientist                                                                           2
Senior Data Scientist / Machine Learning                                                                2
Data Scientist in Artificial Intelligence Early Career                                                  2
Data Scientist - Health Data Analytics                                                                  2
Customer Data Scientist                                                                                 2
Data Scientist SR                                                                                       2
Data Scientist - Alpha Insights                                                                         1
Senior Data Scientist - Algorithms                                                                      1
Data Engineer - ETL                                                                                     1
Data Modeler (Analytical Systems)                                                                       1
Data Science Analyst                                                                                    1
Data Scientist in Translational Medicine                                                                1
Data Analyst 2 (Missionary Department)                                                                  1
Supply Chain Data Analyst                                                                               1
Spectral Scientist/Engineer                                                                             1
Web Data Analyst                                                                                        1
Data Scientist - Sales                                                                                  1
Scientist I/II, Biology                                                                                 1
Data Engineer I                                                                                         1
Senior Data Scientist – Visualization, Novartis AI Innovation Lab                                       1
Product Manager/Data Evangelist                                                                         1
Insurance Financial Data Analyst                                                                        1
Senior Data Analyst/Scientist                                                                           1
Scientist – Cancer Discovery, Molecular Assay                                                           1
Associate Scientist / Sr. Associate Scientist, Antibody Discovery                                       1
Data Architect / Data Modeler                                                                           1
Jr. Data Scientist                                                                                      1
Data Scientist (Warehouse Automation)                                                                   1
Scientist - CVRM Metabolism - in vivo pharmacology                                                      1
Sr. Data Engineer | Big Data SaaS Pipeline                                                              1
Assistant Director/Director, Office of Data Science                                                     1
Manager, Safety Scientist, Medical Safety & Risk Management                                             1
Software Engineer Staff Scientist: Human Language Technologies                                          1
Clinical Scientist, Clinical Development                                                                1
Quality Control Scientist III- Analytical Development                                                   1
Senior Engineer, Data Management Engineering                                                            1

In [9]:
# Convert all job titles to lowercase and remove extra spaces
df['Job_Title']=df['Job_Title'].str.lower().str.strip()

In [10]:
# Again check my job titles
df['Job_Title'].value_counts()

Job_Title
data scientist                                                                                        131
data engineer                                                                                          53
senior data scientist                                                                                  34
data analyst                                                                                           15
senior data engineer                                                                                   14
senior data analyst                                                                                    12
lead data scientist                                                                                     8
marketing data analyst                                                                                  6
sr. data engineer                                                                                       6
machine learning engineer                                                                               5
principal data scientist                                                                                5
r&d specialist/ food scientist                                                                          4
medical laboratory scientist                                                                            4
research scientist                                                                                      4
senior research scientist-machine learning                                                              4
med tech/lab scientist- south coastal lab                                                               4
analytics manager - data mart                                                                           4
food scientist - developer                                                                              4
staff scientist-downstream process development                                                          4
sr. data engineer - contract-to-hire (java)                                                             4
sr. scientist method development                                                                        3
project scientist - auton lab, robotics institute                                                       3
scientist, molecular/cellular biologist                                                                 3
associate scientist, lc/ms biologics                                                                    3
revenue analytics manager                                                                               3
it - data engineer ii                                                                                   3
research scientist, immunology - cancer biology                                                         3
scientist - biomarker and flow cytometry                                                                3
senior scientist - regulatory submissions                                                               3
environmental engineer/scientist                                                                        3
senior data science systems engineer                                                                    3
senior insurance data scientist                                                                         3
associate data analyst- graduate development program                                                    3
scientist - analytical services                                                                         3
principal scientist, chemistry & immunology                                                             3
director ii, data science - grm actuarial                                                               3
scientist/senior scientist, autoimmune                                                                  3
clinical data analyst                                                                                   3
staff data engineer                                                                                     3
consultant - analytics consulting                                                                       3
lead data engineer                                                                                      3
principal scientist, hematology                                                                         3
staff machine learning engineer                                                                         3
software engineer - data visualization                                                                  3
senior data scientist - r&d oncology                                                                    3
principal data scientist (computational chemistry)                                                      3
senior scientist (neuroscience)                                                                         3
machine learning engineer - regulatory                                                                  3
scientist, bacteriology                                                                                 3
associate director, platform and devops- data engineering and aritifical intelligence                   3
clinical laboratory scientist                                                                           3
information security data analyst                                                                       3
sr. data analyst                                                                                        3
data science manager                                                                                    3
scientist                                                                                               3
staff scientist- upstream pd                                                                            2
sr expert data science, advanced visual analytics (associate level)                                     2
sr data analyst - it                                                                                    2
associate machine learning engineer / data scientist may 2020 undergrad                                 2
senior scientist - biostatistician                                                                      2
senior data scientist oncology                                                                          2
associate principal scientist, pharmacogenomics                                                         2
data scientist - systems engineering                                                                    2
data engineer - consultant (charlotte based)                                                            2
data analyst 1, full-time contract worker for up to 12 months                                           2
scientist, immuno-oncology                                                                              2
products data analyst ii                                                                                2
lead data analyst                                                                                       2
data science engineer - mobile                                                                          2
it associate data analyst                                                                               2
scientist, pharmacometrics                                                                              2
business data analyst                                                                                   2
principal, data science - advanced analytics                                                            2
data science project manager                                                                            2
sr scientist, immuno-oncology - oncology                                                                2
data analytics project manager                                                                          2
scientist manufacturing - kentucky bioprocessing                                                        2
director - data, privacy and ai governance                                                              2
staff bi and data engineer                                                                              2
associate data engineer                                                                                 2
research scientist – security and privacy                                                               2
market data analyst                                                                                     2
product engineer – data science                                                                         2
computational chemist/data scientist                                                                    2
director data science                                                                                   2
senior research analytical scientist-non-targeted analysis                                              2
systems engineer ii - data analyst                                                                      2
product engineer – spatial data science and statistical analysis                                        2
managing data scientist/ml engineer                                                                     2
technology-minded, data professional opportunities                                                      2
salesforce analytics consultant                                                                         2
scientist manufacturing pharma - kentucky bioprocessing                                                 2
sr data engineer (sr bi developer)                                                                      2
associate, data science, internal audit                                                                 2
associate environmental scientist - wildlife biologist                                                  2
data modeler - data solutions engineer                                                                  2
marketing data analyst, may 2020 undergrad                                                              2
corporate risk data analyst (sql_ based) - milwaukee or                                                 2
senior manager, epidemiologic data scientist                                                            2
enterprise architect, data                                                                              2
lead big data engineer                                                                                  2
sr software engineer (data scientist)                                                                   2
senior scientist - toxicologist - product integrity (stewardship)                                       2
sr. data engineer (etl developer)                                                                       2
senior data scientist artificial intelligence                                                           2
analytics - business assurance data analyst                                                             2
associate director/director, safety scientist                                                           2
senior scientist, cell pharmacology/assay development                                                   2
data analyst senior                                                                                     2
lead data engineer (python)                                                                             2
senior data scientist 4 artificial intelligence                                                         2
medical lab scientist - mlt                                                                             2
senior operations data analyst, call center operations                                                  2
director ii, data science - grs predictive analytics                                                    2
research computer scientist - research engineer - sr. computer scientist - software development         2
geospatial software developer and data scientist                                                        2
senior lidar data scientist                                                                             2
big data engineer                                                                                       2
medical lab scientist                                                                                   2
senior data & machine learning scientist                                                                2
radar data analyst                                                                                      2
vp, data science                                                                                        2
machine learning research scientist                                                                     2
excel / vba / sql_ data analyst                                                                         2
sr. data scientist ii                                                                                   2
sr. scientist, quantitative translational sciences                                                      2
med tech/lab scientist - laboratory                                                                     2
principal data scientist with over 10 years experience                                                  2
principal scientist - immunologist                                                                      2
sr. scientist - digital & image analysis/computational pathology                                        2
digital marketing & ecommerce data analyst                                                              2
analytics manager                                                                                       2
scientist, analytical development                                                                       2
risk and analytics it, data scientist                                                                   2
senior scientist - neuroscience                                                                         2
data engineer 5 - contract (remote)                                                                     2
staff data scientist                                                                                    2
data scientist (actuary, fsa or asa)                                                                    2
pricipal scientist molecular and cellular biologist                                                     2
sr. data scientist - analytics, personalized healthcare (phc)                                           2
bi & platform analytics manager                                                                         2
pl actuarial-lead data scientist                                                                        2
pv scientist                                                                                            2
data scientist - algorithms & inference                                                                 2
data scientist - quantitative                                                                           2
data scientist, office of data science                                                                  2
college hire - data scientist - open to december 2019 graduates                                         2
senior risk data scientist                                                                              2
staff data scientist - technology                                                                       2
data scientist / machine learning expert                                                                2
clinical data scientist                                                                                 2
associate data analyst                                                                                  2
digital health data scientist                                                                           2
senior data scientist / machine learning                                                                2
data scientist in artificial intelligence early career                                                  2
data scientist - health data analytics                                                                  2
customer data scientist                                                                                 2
data scientist sr                                                                                       2
data scientist - alpha insights                                                                         1
senior data scientist - algorithms                                                                      1
data engineer - etl                                                                                     1
data modeler (analytical systems)                                                                       1
data science analyst                                                                                    1
data scientist in translational medicine                                                                1
data analyst 2 (missionary department)                                                                  1
supply chain data analyst                                                                               1
spectral scientist/engineer                                                                             1
web data analyst                                                                                        1
data scientist - sales                                                                                  1
scientist i/ii, biology                                                                                 1
data engineer i                                                                                         1
senior data scientist – visualization, novartis ai innovation lab                                       1
product manager/data evangelist                                                                         1
insurance financial data analyst                                                                        1
senior data analyst/scientist                                                                           1
scientist – cancer discovery, molecular assay                                                           1
associate scientist / sr. associate scientist, antibody discovery                                       1
data architect / data modeler                                                                           1
jr. data scientist                                                                                      1
data scientist (warehouse automation)                                                                   1
scientist - cvrm metabolism - in vivo pharmacology                                                      1
sr. data engineer | big data saas pipeline                                                              1
assistant director/director, office of data science                                                     1
manager, safety scientist, medical safety & risk management                                             1
software engineer staff scientist: human language technologies                                          1
clinical scientist, clinical development                                                                1
quality control scientist iii- analytical development                                                   1
senior engineer, data management engineering                                                            1

In [11]:
# Import re for text pattern matching and cleaning
import re

In [12]:
# remove special characters
df['Job_Title']=df['Job_Title'].apply(lambda x: re.sub(r'[^a-zA-Z0-9\s]', ' ', x))

In [13]:
df['Job_Title'].value_counts()

Job_Title
data scientist                                                                                        131
data engineer                                                                                          53
senior data scientist                                                                                  34
data analyst                                                                                           15
senior data engineer                                                                                   14
senior data analyst                                                                                    12
lead data scientist                                                                                     8
marketing data analyst                                                                                  6
sr  data engineer                                                                                       6
machine learning engineer                                                                               5
principal data scientist                                                                                5
r d specialist  food scientist                                                                          4
medical laboratory scientist                                                                            4
research scientist                                                                                      4
senior research scientist machine learning                                                              4
med tech lab scientist  south coastal lab                                                               4
analytics manager   data mart                                                                           4
food scientist   developer                                                                              4
staff scientist downstream process development                                                          4
sr  data engineer   contract to hire  java                                                              4
sr  scientist method development                                                                        3
project scientist   auton lab  robotics institute                                                       3
scientist  molecular cellular biologist                                                                 3
associate scientist  lc ms biologics                                                                    3
revenue analytics manager                                                                               3
it   data engineer ii                                                                                   3
research scientist  immunology   cancer biology                                                         3
scientist   biomarker and flow cytometry                                                                3
senior scientist   regulatory submissions                                                               3
environmental engineer scientist                                                                        3
senior data science systems engineer                                                                    3
senior insurance data scientist                                                                         3
associate data analyst  graduate development program                                                    3
scientist   analytical services                                                                         3
principal scientist  chemistry   immunology                                                             3
director ii  data science   grm actuarial                                                               3
scientist senior scientist  autoimmune                                                                  3
clinical data analyst                                                                                   3
staff data engineer                                                                                     3
consultant   analytics consulting                                                                       3
lead data engineer                                                                                      3
principal scientist  hematology                                                                         3
staff machine learning engineer                                                                         3
software engineer   data visualization                                                                  3
senior data scientist   r d oncology                                                                    3
principal data scientist  computational chemistry                                                       3
senior scientist  neuroscience                                                                          3
machine learning engineer   regulatory                                                                  3
scientist  bacteriology                                                                                 3
associate director  platform and devops  data engineering and aritifical intelligence                   3
clinical laboratory scientist                                                                           3
information security data analyst                                                                       3
sr  data analyst                                                                                        3
data science manager                                                                                    3
scientist                                                                                               3
staff scientist  upstream pd                                                                            2
sr expert data science  advanced visual analytics  associate level                                      2
sr data analyst   it                                                                                    2
associate machine learning engineer   data scientist may 2020 undergrad                                 2
senior scientist   biostatistician                                                                      2
senior data scientist oncology                                                                          2
associate principal scientist  pharmacogenomics                                                         2
data scientist   systems engineering                                                                    2
data engineer   consultant  charlotte based                                                             2
data analyst 1  full time contract worker for up to 12 months                                           2
scientist  immuno oncology                                                                              2
products data analyst ii                                                                                2
lead data analyst                                                                                       2
data science engineer   mobile                                                                          2
it associate data analyst                                                                               2
scientist  pharmacometrics                                                                              2
business data analyst                                                                                   2
principal  data science   advanced analytics                                                            2
data science project manager                                                                            2
sr scientist  immuno oncology   oncology                                                                2
data analytics project manager                                                                          2
scientist manufacturing   kentucky bioprocessing                                                        2
director   data  privacy and ai governance                                                              2
staff bi and data engineer                                                                              2
associate data engineer                                                                                 2
research scientist   security and privacy                                                               2
market data analyst                                                                                     2
product engineer   data science                                                                         2
computational chemist data scientist                                                                    2
director data science                                                                                   2
senior research analytical scientist non targeted analysis                                              2
systems engineer ii   data analyst                                                                      2
product engineer   spatial data science and statistical analysis                                        2
managing data scientist ml engineer                                                                     2
technology minded  data professional opportunities                                                      2
salesforce analytics consultant                                                                         2
scientist manufacturing pharma   kentucky bioprocessing                                                 2
sr data engineer  sr bi developer                                                                       2
associate  data science  internal audit                                                                 2
associate environmental scientist   wildlife biologist                                                  2
data modeler   data solutions engineer                                                                  2
marketing data analyst  may 2020 undergrad                                                              2
corporate risk data analyst  sql  based    milwaukee or                                                 2
senior manager  epidemiologic data scientist                                                            2
enterprise architect  data                                                                              2
lead big data engineer                                                                                  2
sr software engineer  data scientist                                                                    2
senior scientist   toxicologist   product integrity  stewardship                                        2
sr  data engineer  etl developer                                                                        2
senior data scientist artificial intelligence                                                           2
analytics   business assurance data analyst                                                             2
associate director director  safety scientist                                                           2
senior scientist  cell pharmacology assay development                                                   2
data analyst senior                                                                                     2
lead data engineer  python                                                                              2
senior data scientist 4 artificial intelligence                                                         2
medical lab scientist   mlt                                                                             2
senior operations data analyst  call center operations                                                  2
director ii  data science   grs predictive analytics                                                    2
research computer scientist   research engineer   sr  computer scientist   software development         2
geospatial software developer and data scientist                                                        2
senior lidar data scientist                                                                             2
big data engineer                                                                                       2
medical lab scientist                                                                                   2
senior data   machine learning scientist                                                                2
radar data analyst                                                                                      2
vp  data science                                                                                        2
machine learning research scientist                                                                     2
excel   vba   sql  data analyst                                                                         2
sr  data scientist ii                                                                                   2
sr  scientist  quantitative translational sciences                                                      2
med tech lab scientist   laboratory                                                                     2
principal data scientist with over 10 years experience                                                  2
principal scientist   immunologist                                                                      2
sr  scientist   digital   image analysis computational pathology                                        2
digital marketing   ecommerce data analyst                                                              2
analytics manager                                                                                       2
scientist  analytical development                                                                       2
risk and analytics it  data scientist                                                                   2
senior scientist   neuroscience                                                                         2
data engineer 5   contract  remote                                                                      2
staff data scientist                                                                                    2
data scientist  actuary  fsa or asa                                                                     2
pricipal scientist molecular and cellular biologist                                                     2
sr  data scientist   analytics  personalized healthcare  phc                                            2
bi   platform analytics manager                                                                         2
pl actuarial lead data scientist                                                                        2
pv scientist                                                                                            2
data scientist   algorithms   inference                                                                 2
data scientist   quantitative                                                                           2
data scientist  office of data science                                                                  2
college hire   data scientist   open to december 2019 graduates                                         2
senior risk data scientist                                                                              2
staff data scientist   technology                                                                       2
data scientist   machine learning expert                                                                2
clinical data scientist                                                                                 2
associate data analyst                                                                                  2
digital health data scientist                                                                           2
senior data scientist   machine learning                                                                2
data scientist in artificial intelligence early career                                                  2
data scientist   health data analytics                                                                  2
customer data scientist                                                                                 2
data scientist sr                                                                                       2
data scientist   alpha insights                                                                         1
senior data scientist   algorithms                                                                      1
data engineer   etl                                                                                     1
data modeler  analytical systems                                                                        1
data science analyst                                                                                    1
data scientist in translational medicine                                                                1
data analyst 2  missionary department                                                                   1
supply chain data analyst                                                                               1
spectral scientist engineer                                                                             1
web data analyst                                                                                        1
data scientist   sales                                                                                  1
scientist i ii  biology                                                                                 1
data engineer i                                                                                         1
senior data scientist   visualization  novartis ai innovation lab                                       1
product manager data evangelist                                                                         1
insurance financial data analyst                                                                        1
senior data analyst scientist                                                                           1
scientist   cancer discovery  molecular assay                                                           1
associate scientist   sr  associate scientist  antibody discovery                                       1
data architect   data modeler                                                                           1
jr  data scientist                                                                                      1
data scientist  warehouse automation                                                                    1
scientist   cvrm metabolism   in vivo pharmacology                                                      1
sr  data engineer   big data saas pipeline                                                              1
assistant director director  office of data science                                                     1
manager  safety scientist  medical safety   risk management                                             1
software engineer staff scientist  human language technologies                                          1
clinical scientist  clinical development                                                                1
quality control scientist iii  analytical development                                                   1
senior engineer  data management engineering                                                            1

In [14]:
# Check my job titles category based on my Job_title
df['job_title_sim'].value_counts()

job_title_sim
data scientist                    313
other scientist                   143
data engineer                     119
analyst                           101
machine learning engineer          22
Data scientist project manager     16
na                                 10
data analitics                      8
data modeler                        5
director                            5
Name: count, dtype: int64

In [15]:
# Job_Title and job_title_sim columns for comparison
df[['Job_Title','job_title_sim']].head(101)

                                             Job_Title    job_title_sim
0                                       data scientist   data scientist
1                            healthcare data scientist   data scientist
2                                       data scientist   data scientist
3                                       data scientist   data scientist
4                                       data scientist   data scientist
5                                       data scientist   data scientist
6                                       data scientist   data scientist
7                                       data scientist   data scientist
8                                   research scientist  other scientist
9                                       data scientist   data scientist
10                                      data scientist   data scientist
11                                      data scientist   data scientist
12                   staff data scientist   technology   data scientist
13                                        data analyst          analyst
14                                      data scientist   data scientist
15                                     data engineer i    data engineer
16                             scientist i ii  biology  other scientist
17                             customer data scientist   data scientist
18              data scientist   health data analytics   data scientist
19                                      data scientist   data scientist
20                                      data scientist   data scientist
21            senior data scientist   machine learning   data scientist
22                       data scientist   quantitative   data scientist
23                                      data scientist   data scientist
24                                      data scientist   data scientist
25                       digital health data scientist   data scientist
26                                      data scientist   data scientist
27                              associate data analyst          analyst
28                             clinical data scientist   data scientist
29                                      data scientist   data scientist
30                                      data scientist   data scientist
31                                      data scientist   data scientist
32            data scientist   machine learning expert   data scientist
33                                      data scientist   data scientist
34                                      data scientist   data scientist
35                                    web data analyst          analyst
36                                      data scientist   data scientist
37                                      data scientist   data scientist
38                               senior data scientist   data scientist
39                                       data engineer    data engineer
40                                        data analyst          analyst
41                                       data engineer    data engineer
42             data scientist   algorithms   inference   data scientist
43                                           scientist  other scientist
44                               senior data scientist   data scientist
45                                      data scientist   data scientist
46                                 lead data scientist   data scientist
47                              associate data analyst          analyst
48                         spectral scientist engineer  other scientist
49   college hire   data scientist   open to decemb...   data scientist
50                                      data scientist   data scientist
51              data scientist  office of data science   data scientist
52                                data science analyst   data scientist
53                                      data scientist   data scientist
54                                      data scientist   data scientist
55                                      data scientist   data scientist
56                                      data scientist   data scientist
57                                      data scientist   data scientist
58                                      data scientist   data scientist
59                                      data scientist   data scientist
60                               senior data scientist   data scientist
61                                      data scientist   data scientist
62                          senior risk data scientist   data scientist
63   data scientist in artificial intelligence earl...   data scientist
64                                      data scientist   data scientist
65                                      data scientist   data scientist
66                                      data scientist   data scientist
67                           data scientist   research   data scientist
68                                      data scientist   data scientist
69                         r d data analysis scientist  other scientist
70                                analytics consultant   data analitics
71                              director  data science   data scientist
72                                           scientist  other scientist
73                                   data scientist sr   data scientist
74                                      data scientist   data scientist
75                               r d sr data scientist   data scientist
76         customer data scientist sales engineer  bay   data scientist
77                                  research scientist  other scientist
78                                      data scientist   data scientist
79                                      data scientist   data scientist
80                                      data scientist   data scientist
81                           jr  business data analyst          analyst
82                                      data scientist   data scientist
83                                        data analyst          analyst
84                                       data engineer    data engineer
85                                        data analyst          analyst
86                   staff data scientist   technology   data scientist
87                                      data scientist   data scientist
88                                      data scientist   data scientist
89                          data management specialist               na
90                             e commerce data analyst          analyst
91                                    sr  scientist ii  other scientist
92                            insurance data scientist   data scientist
93                                        data modeler     data modeler
94                            data analyst   scientist          analyst
95                                           scientist  other scientist
96                                      data scientist   data scientist
97                                      data scientist   data scientist
98                                        data analyst          analyst
99                                 lead data scientist   data scientist
100                                     data scientist   data scientist

In [16]:
# Create mapping for standardize job titles into meaningful categories
job_map = {
    'data scientist': 'Data Scientist',
    'other scientist': 'Other Scientist',
    'data engineer': 'Data Engineer',
    'machine learning engineer': 'ML Engineer',
    'analyst': 'Data Analyst',
    'data analitics': 'Data Analyst',
    'data modeler': 'Data Engineer',
    'Data scientist project manager': 'Manager',
    'director': 'Director',
    'na': 'Other'
}

In [17]:
# job_categories from job_title_sim using pre_defined
df['Job_Category'] = df['job_title_sim'].map(job_map)

In [18]:
# Count the number of job_category
df['Job_Category'].value_counts()

Job_Category
Data Scientist     313
Other Scientist    143
Data Engineer      124
Data Analyst       109
ML Engineer         22
Manager             16
Other               10
Director             5
Name: count, dtype: int64

In [19]:
# Again display columns and rows to understand data
df.head(100)

,Job_Title,Salary_Estimate,Rating,Company_Name,Location,Headquarters,Size,Founded,Type_of_ownership,Industry,Sector,Revenue,Competitors,Hourly,Employer_provided,Lower_Salary,Upper_Salary,Avg_SalaryK,company_txt,Job_Location,Age,Python,spark,aws,excel,sql_,sas,keras,pytorch,scikit,tensor,hadoop,tableau,bi,flink,mongo,google_an,job_title_sim,seniority_by_title,Degree,Job_Category
0,data scientist,$53K-$91K (Glassdoor est.),3.8,Tecolote Research\n3.8,"Albuquerque, NM","Goleta, CA",501 - 1000,1973,Company - Private,Aerospace & Defense,Aerospace & Defense,$50 to $100 million (USD),-1,0,0,53,91,72.0,Tecolote Research,NM,48,1,0,0,1,0,1,0,0,0,0,0,1,1,0,0,0,data scientist,na,M,Data Scientist
1,healthcare data scientist,$63K-$112K (Glassdoor est.),3.4,University of Maryland Medical System\n3.4,"Linthicum, MD","Baltimore, MD",10000+,1984,Other Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1,0,0,63,112,87.5,University of Maryland Medical System,MD,37,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,data scientist,na,M,Data Scientist
2,data scientist,$80K-$90K (Glassdoor est.),4.8,KnowBe4\n4.8,"Clearwater, FL","Clearwater, FL",501 - 1000,2010,Company - Private,Security Services,Business Services,$100 to $500 million (USD),-1,0,0,80,90,85.0,KnowBe4,FL,11,1,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,data scientist,na,M,Data Scientist
3,data scientist,$56K-$97K (Glassdoor est.),3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 - 5000,1965,Government,Energy,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa...",0,0,56,97,76.5,PNNL,WA,56,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,data scientist,na,na,Data Scientist
4,data scientist,$86K-$143K (Glassdoor est.),2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 - 200,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee",0,0,86,143,114.5,Affinity Solutions,NY,23,1,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,data scientist,na,na,Data Scientist
5,data scientist,$71K-$119K (Glassdoor est.),3.4,CyrusOne\n3.4,"Dallas, TX","Dallas, TX",201 - 500,2000,Company - Public,Real Estate,Real Estate,$1 to $2 billion (USD),"Digital Realty, CoreSite, Equinix",0,0,71,119,95.0,CyrusOne,TX,21,1,0,1,1,1,0,0,0,0,0,0,0,1,0,1,0,data scientist,na,na,Data Scientist
6,data scientist,$54K-$93K (Glassdoor est.),4.1,ClearOne Advantage\n4.1,"Baltimore, MD","Baltimore, MD",501 - 1000,2008,Company - Private,Banks & Credit Unions,Finance,Unknown / Non-Applicable,-1,0,0,54,93,73.5,ClearOne Advantage,MD,13,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,data scientist,na,na,Data Scientist
7,data scientist,$86K-$142K (Glassdoor est.),3.8,Logic20/20\n3.8,"San Jose, CA","Seattle, WA",201 - 500,2005,Company - Private,Consulting,Business Services,$25 to $50 million (USD),-1,0,0,86,142,114.0,Logic20/20,CA,16,1,1,1,1,1,0,0,1,0,1,0,0,0,0,0,0,data scientist,na,M,Data Scientist
8,research scientist,$38K-$84K (Glassdoor est.),3.3,Rochester Regional Health\n3.3,"Rochester, NY","Rochester, NY",10000+,2014,Hospital,Health Care Services & Hospitals,Health Care,$500 million to $1 billion (USD),-1,0,0,38,84,61.0,Rochester Regional Health,NY,7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,other scientist,na,P,Other Scientist
9,data scientist,$120K-$160K (Glassdoor est.),4.6,<intent>\n4.6,"New York, NY","New York, NY",51 - 200,2009,Company - Private,Internet,Information Technology,$100 to $500 million (USD),"Clicktripz, SmarterTravel",0,0,120,160,140.0,<intent>,NY,12,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,data scientist,na,na,Data Scientist
10,data scientist,$126K-$201K (Glassdoor est.),3.5,Wish\n3.5,"San Jose, CA","San Francisco, CA",501 - 1000,2011,Company - Private,Other Retail Stores,Retail,$1 to $2 billion (USD),-1,0,0,126,201,163.5,Wish,CA,10,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,data scientist,na,na,Data Scientist
11,data scientist,$64K-$106K (Glassdoor est.),4.1,ManTech\n4.1,"Chantilly, VA","Herndon, VA",5001 - 10000,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1,0,0,64,106,85.0,ManTech,VA,53,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,data scientist,na,na,Data Scientist
12,staff data scientist technology,$106K-$172K (Glassdoor est.),3.2,Walmart\n3.2,"Plano, TX","Bentonville, AR",10000+,1962,Company - Public,"Department, Clothing, & Shoe Stores",Retail,$10+ billion (USD),"Target, Costco Wholesale, Amazon",0,0,106,172,139.0,Walmart,TX,59,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,data scientist,na,M,Data Scientist
13,data analyst,$46K-$85K (Glassdoor est.),4.1,Yesler\n4.1,"Seattle, WA","Seattle, WA",201 - 500,2012,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,-1,0,0,46,85,65.5,Yesler,WA,9,1,1,1,1,1,0,0,0,0,0,0,1,1,0,0,0,analyst,na,na,Data Analyst
14,data scientist,$83K-$144K (Glassdoor est.),3.7,Takeda Pharmaceuticals\n3.7,"Cambridge, MA","OSAKA, Japan",10000+,1781,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),"Novartis, Baxter, Pfizer",0,0,83,144,113.5,Takeda Pharmaceuticals,MA,240,1,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,data scientist,na,M,Data Scientist
15,data engineer i,$102K-$190K (Glassdoor est.),3.6,Audible\n3.6,"Newark, NJ","Newark, NJ",1001 - 5000,1995,Subsidiary or Business Segment,Motion Picture Production & Distribution,Media,Unknown / Non-Applicable,-1,0,0,102,190,146.0,Audible,NJ,26,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,data engineer,na,na,Data Engineer
16,scientist i ii biology,$67K-$137K (Glassdoor est.),3.9,Blueprint Medicines\n3.9,"Cambridge, MA","Cambridge, MA",51 - 200,2011,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$1 to $5 million (USD),"bluebird bio, Agios Pharmaceuticals, Celgene",0,0,67,137,102.0,Blueprint Medicines,MA,10,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,other scientist,na,P,Other Scientist
17,customer data scientist,$118K-$189K (Glassdoor est.),4.3,h2o.ai\n4.3,"Mountain View, CA","Mountain View, CA",201 - 500,2011,Company - Private,Enterprise Software & Network Solutions,Information Technology,Unknown / Non-Applicable,-1,0,0,118,189,153.5,h2o.ai,CA,10,1,1,1,1,0,0,0,0,0,0,1,0,0,0,0,0,data scientist,na,M,Data Scientist
18,data scientist health data analytics,$110K-$175K (Glassdoor est.),4.2,Nuna\n4.2,"San Francisco, CA","San Francisco, CA",51 - 200,2010,Company - Private,Enterprise Software & Network Solutions,Information Technology,Unknown / Non-Applicable,-1,0,0,110,175,142.5,Nuna,CA,11,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,data scientist,na,na,Data Scientist
19,data scientist,$64K-$111K (Glassdoor est.),4.0,Pinnacol Assurance\n4.0,"Denver, CO","Denver, CO",501 - 1000,1915,Nonprofit Organization,Insurance Carriers,Insurance,$500 million to $1 billion (USD),-1,0,0,64,111,87.5,Pinnacol Assurance,CO,106,1,0,0,1,1,0,1,1,1,1,0,0,0,0,0,0,data scientist,na,M,Data Scientist
20,data scientist,$81K-$130K (Glassdoor est.),3.2,Porch\n3.2,"Seattle, WA","Seattle, WA",201 - 500,2012,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,"Angie's List, HomeAdvisor, Thumbtack",0,0,81,130,105.5,Porch,WA,9,1,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,data scientist,na,M,Data Scientist
21,senior data scientist machine learning,$73K-$119K (Glassdoor est.),3.9,Health IQ\n3.9,"Dallas, TX","Mountain View, CA",201 - 500,2013,Company - Private,Insurance Agencies & Brokerages,Insurance,Unknown / Non-Applicable,-1,0,0,73,119,96.0,Health IQ,TX,8,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,data scientist,sr,P,Data Scientist
22,data scientist quantitative,$86K-$139K (Glassdoor est.),3.8,Truckstop.com\n3.8,"Chicago, IL","New Plymouth, ID",501 - 1000,1995,Company - Private,Logistics & Supply Chain,Transportation & Logistics,Unknown / Non-Applicable,-1,0,0,86,139,112.5,Truckstop.com,IL,26,1,0,1,1,1,0,0,0,0,0,0,0,0,0,1,0,data scientist,na,M,Data Scientist
23,data scientist,$63K-$105K (Glassdoor est.),4.3,SMC 3\n4.3,"Louisville, KY","Peachtree City, GA",51 - 200,1935,Nonprofit Organization,Logistics & Supply Chain,Transportation & Logistics,$10 to $25 million (USD),-1,0,0,63,105,84.0,SMC 3,KY,86,1,0,0,1,1,0,0,0,0,0,0,1,0,0,0,0,data scientist,na,M,Data Scientist
24,data scientist,$109K-$177K (Glassdoor est.),4.0,Novetta\n4.0,"Herndon, VA","Mc Lean, VA",501 - 1000,2012,Company - Private,Enterprise Software & Network Solutions,Information Technology,$100 to $500 million (USD),"Leidos, CACI International, Booz Allen Hamilton",0,0,109,177,143.0,Novetta,VA,9,1,0,1,0,0,0,1,0,0,1,0,0,0,0,0,0,data scientist,na,na,Data Scientist
25,digital health data scientist,$63K-$110K (Glassdoor est.),4.0,Pfizer\n4.0,"Cambridge, MA","New York, NY",10000+,1849,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),-1,0,0,63,110,86.5,Pfizer,MA,172,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,data scientist,na,na,Data Scientist
26,data scientist,$75K-$124K (Glassdoor est.),3.5,First Tech Federal Credit Union\n3.5,"Hillsboro, OR","San Jose, CA",1001 - 5000,1952,Company - Private,Banks & Credit Unions,Finance,$100 to $500 million (USD),-1,0,0,75,124,99.5,First Tech Federal Credit Union,OR,69,1,1,1,1,1,0,1,0,1,1,0,1,0,0,0,0,data scientist,na,na,Data Scientist
27,associate data analyst,$34K-$61K (Glassdoor est.),3.7,The Hanover Insurance Group\n3.7,"Worcester, MA","Worcester, MA",5001 - 10000,1852,Company - Public,Insurance Carriers,Insurance,$5 to $10 billion (USD),-1,0,0,34,61,47.5,The Hanover Insurance Group,MA,169,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,analyst,na,na,Data Analyst
28,clinical data scientist,$63K-$105K (Glassdoor est.),4.0,Pfizer\n4.0,"Groton, CT","New York, NY",10000+,1849,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),-1,0,0,63,105,84.0,Pfizer,CT,172,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,data scientist,na,M,Data Scientist
29,data scientist,$80K-$90K (Glassdoor est.),4.8,KnowBe4\n4.8,"Clearwater, FL","Clearwater, FL",501 - 1000,2010,Company - Private,Security Services,Business Services,$100 to $500 million (USD),-1,0,0,80,90,85.0,KnowBe4,FL,11,1,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,data scientist,na,M,Data Scientist
30,data scientist,$56K-$97K (Glassdoor est.),3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 - 5000,1965,Government,Energy,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa...",0,0,56,97,76.5,PNNL,WA,56,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,data scientist,na,na,Data Scientist
31,data scientist,$72K-$120K (Glassdoor est.),3.6,Amrock\n3.6,"Detroit, MI","Detroit, MI",1001 - 5000,1997,Company - Private,Real Estate,Real Estate,$500 million to $1 billion (USD),-1,0,0,72,120,96.0,Amrock,MI,24,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,data scientist,na,M,Data Scientist
32,data scientist machine learning expert,$86K-$143K (Glassdoor est.),3.8,Novartis\n3.8,"Cambridge, MA","Basel, Switzerland",10000+,1996,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),-1,0,0,86,143,114.5,Novartis,MA,25,1,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,data scientist,na,na,Data Scientist
33,data scientist,$93K-$149K (Glassdoor est.),3.8,Juniper Networks\n3.8,"Sunnyvale, CA","Sunnyvale, CA",5001 - 10000,1996,Company - Public,Telecommunications Services,Telecommunications,$2 to $5 billion (USD),-1,0,0,93,149,121.0,Juniper Networks,CA,25,1,1,0,1,1,0,1,0,1,1,0,0,0,0,1,0,data scientist,na,M,Data Scientist
34,data scientist,$85K-$140K (Glassdoor est.),4.7,New England Biolabs\n4.7,"Ipswich, MA","Ipswich, MA",201 - 500,1974,Company - Private,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable,"Thermo Fisher Scientific, Enzymatics, Illumina",0,0,85,140,112.5,New England Biolabs,MA,47,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,data scientist,na,na,Data Scientist
35,web data analyst,$77K-$135K (Glassdoor est.),4.2,Clarity Insights\n4.2,"San Jose, CA","Chicago, IL",201 - 500,2008,Company - Private,IT Services,Information Technology,Unknown / Non-Applicable,-1,0,0,77,135,106.0,Clarity Insights,CA,13,1,0,0,1,1,0,0,0,0,0,0,1,1,0,0,0,analyst,na,na,Data Analyst
36,data scientist,$82K-$132K (Glassdoor est.),3.5,Esri\n3.5,"Redlands, CA","Redlands, CA",1001 - 5000,1969,Company - Private,Computer Hardware & Software,Information Technology,$1 to $2 billion (USD),Pitney Bowes,0,0,82,132,107.0,Esri,CA,52,1,1,1,0,0,0,0,0,0,0,1,1,0,0,1,0,data scientist,na,M,Data Scientist
37,data scientist,$83K-$137K (Glassdoor est.),4.7,Systems & Technology Research\n4.7,"Woburn, MA","Woburn, MA",201 - 500,2010,Company - Private,Aerospace & Defense,Aerospace & Defense,$100 to $500 million (USD),-1,0,0,83,137,110.0,Systems & Technology Research,MA,11,1,1,0,1,1,0,0,1,1,1,1,0,0,0,0,0,data scientist,na,P,Data Scientist
38,senior data scientist,$115K-$180K (Glassdoor est.),3.5,Sartorius\n3.5,"Fremont, CA","Gottingen, Germany",5001 - 10000,1870,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$1 to $2 billion (USD),-1,0,0,115,180,147.5,Sartorius,CA,151,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,data scientist,sr,M,Data Scientist
39,data engineer,$74K-$138K (Glassdoor est.),3.5,Lancer Insurance\n3.5,"Long Beach, NY","Long Beach, NY",201 - 500,1985,Company - Private,Insurance Carriers,Insurance,$100 to $500 million (USD),-1,0,0,74,138,106.0,Lancer Insurance,NY,36,1,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,data engineer,na,M,Data Engineer
40,data analyst,$64K-$112K (Glassdoor est.),4.2,Sauce Labs\n4.2,"San Francisco, CA","San Francisco, CA",201 - 500,2008,Company - Private,IT Services,Information Technology,$50 to $100 million (USD),"BrowserStack, Selenium Master, Perfecto Mobile",0,0,64,112,88.0,Sauce Labs,CA,13,1,0,1,1,1,0,0,0,0,0,0,1,0,0,1,0,analyst,na,na,Data Analyst
41,data engineer,$68K-$129K (Glassdoor est.),3.6,Persivia\n3.6,"Marlborough, MA","Lowell, MA",Jan-50,-1,Company - Private,-1,-1,Less than $1 million (USD),-1,0,0,68,129,98.5,Persivia,MA,-1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,data engineer,na,na,Data Engineer
42,data scientist algorithms inference,$110K-$175K (Glassdoor est.),4.2,Nuna\n4.2,"San Francisco, CA","San Francisco, CA",51 - 200,2010,Company - Private,Enterprise Software & Network Solutions,Information Technology,Unknown / Non-Applicable,-1,0,0,110,175,142.5,Nuna,CA,11,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,data scientist,na,M,Data Scientist
43,scientist,$52K-$113K (Glassdoor est.),3.4,Edgewell Personal Care\n3.4,"Allendale, NJ","Shelton, CT",5001 - 10000,2015,Company - Public,Consumer Products Manufacturing,Manufacturing,$2 to $5 billion (USD),"Unilever, Procter & Gamble, Henkel",0,0,52,113,82.5,Edgewell Personal Care,NJ,6,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,other scientist,na,M,Other Scientist
44,senior data scientist,$110K-$150K(Employer est.),4.3,Equity Residential\n4.3,"Chicago, IL","Chicago, IL",1001 - 5000,1993,Company - Public,Real Estate,Real Estate,$2 to $5 billion (USD),"UDR, AvalonBay Communities, Essex Property Trust",0,0,110,150,130.0,Equity Residential,IL,28,1,1,0,1,1,0,0,0,1,0,1,1,1,0,0,0,data scientist,sr,M,Data Scientist
45,data scientist,Employer Provided Salary:$150K-$160K,5.0,BPA Services\n5.0,"Washington, DC","Alexandria, VA",unknown,-1,Company - Private,Enterprise Software & Network Solutions,Information Technology,Unknown / Non-Applicable,-1,0,1,150,160,155.0,BPA Services,DC,-1,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,data scientist,na,na,Data Scientist
46,lead data scientist,$158K-$211K (Glassdoor est.),3.7,Visa Inc.\n3.7,"Bellevue, WA","Foster City, CA",10000+,1958,Company - Public,IT Services,Information Technology,$10+ billion (USD),"American Express, Mastercard, Discover",0,0,158,211,184.5,Visa Inc.,WA,63,1,0,0,1,1,1,0,0,0,0,0,1,0,0,0,0,data scientist,sr,na,Data Scientist
47,associate data analyst,$20K-$39K (Glassdoor est.),3.1,Intrado\n3.1,"Longmont, CO","Omaha, NE",5001 - 10000,1986,Company - Private,Enterprise Software & Network Solutions,Information Technology,$2 to $5 billion (USD),-1,0,0,20,39,29.5,Intrado,CO,35,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,analyst,na,M,Data Analyst
48,spectral scientist engineer,$56K-$117K (Glassdoor est.),4.7,Centauri\n4.7,"Beavercreek, OH","Chantilly, VA",501 - 1000,1999,Company - Private,Aerospace & Defense,Aerospace & Defense,$100 to $500 million (USD),"TASC, Vencore, Booz Allen Hamilton",0,0,56,117,86.5,Centauri,OH,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,other scientist,na,M,Other Scientist
49,college hire data scientist open to decemb...,$63K-$99K (Glassdoor est.),3.7,Caterpillar\n3.7,"Peoria, IL","Deerfield, IL",10000+,1925,Company - Public,Industrial Manufacturing,Manufacturing,$10+ billion (USD),"John Deere, Komatsu, CNH Industrial",0,0,63,99,81.0,Caterpillar,IL,96,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,data scientist,na,na,Data Scientist
50,data scientist,$68K-$114K (Glassdoor est.),3.8,Zimmerman Advertising\n3.8,"Fort Lauderdale, FL","Fort Lauderdale, FL",501 - 1000,1984,Subsidiary or Business Segment,Advertising & Marketing,Business Services,Unknown / Non-Applicable,-1,0,0,68,114,91.0,Zimmerman Advertising,FL,37,1,0,0,1,1,0,0,0,0,0,1,1,0,0,0,0,data scientist,na,na,Data Scientist
51,data scientist office of data science,$86K-$143K (Glassdoor est.),3.3,Liberty Mutual Insurance\n3.3,"Boston, MA","Boston, MA",10000+,1912,Company - Private,Insurance Carriers,Insurance,$10+ billion (USD),"Travelers, Allstate, State Farm",0,0,86,143,114.5,Liberty Mutual Insurance,MA,109,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,data scientist,na,na,Data Scientist
52,data science analyst,$41K-$95K (Glassdoor est.),4.6,"Torch Technologies, Inc.\n4.6","Huntsville, AL","Huntsville, AL",1001 - 5000,2002,Company - Private,Aerospace & Defense,Aerospace & Defense,$100 to $500 million (USD),-1,0,0,41,95,68.0,"Torch Technologies, Inc.",AL,19,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,data scientist,na,na,Data Scientist
53,data scientist,$86K-$144K (Glassdoor est.),3.7,Swiss Re\n3.7,"Armonk, NY","Zurich, Switzerland",10000+,1863,Company - Public,Insurance Agencies & Brokerages,Insurance,$10+ billion (USD),"Munich Re, Hannover RE, SCOR",0,0,86,144,115.0,Swiss Re,NY,158,1,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,data scientist,na,M,Data Scientist
54,data scientist,$80K-$139K (Glassdoor est.),3.7,Northrop Grumman\n3.7,"San Diego, CA","Falls Church, VA",10000+,1939,Company - Public,Aerospace & Defense,Aerospace & Defense,$10+ billion (USD),-1,0,0,80,139,109.5,Northrop Grumman,CA,82,0,0,0,1,1,0,0,0,0,0,0,1,0,0,0,0,data scientist,na,na,Data Scientist
55,data scientist,$56K-$95K (Glassdoor est.),3.5,Sartorius\n3.5,"Albuquerque, NM","Gottingen, Germany",5001 - 10000,1870,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$1 to $2 billion (USD),-1,0,0,56,95,75.5,Sartorius,NM,151,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,data scientist,na,M,Data Scientist
56,data scientist,$120K-$189K (Glassdoor est.),4.1,Netskope\n4.1,"San Francisco, CA","Santa Clara, CA",501 - 1000,2012,Company - Private,Enterprise Software & Network Solutions,Information Technology,Unknown / Non-Applicable,"Skyhigh Networks, Zscaler, NortonLifeLock",0,0,120,189,154.5,Netskope,CA,9,1,1,0,1,0,0,0,0,0,1,0,0,0,1,0,0,data scientist,na,P,Data Scientist
57,data scientist,$111K-$176K (Glassdoor est.),4.7,1904labs\n4.7,"Saint Louis, MO","Saint Louis, MO",51 - 200,2016,Company - Private,IT Services,Information Technology,Unknown / Non-Applicable,"Slalom, Daugherty Business Solutions",0,0,111,176,143.5,1904labs,MO,5,1,1,0,0,1,0,1,0,1,1,0,0,0,0,0,0,data scientist,na,na,Data Scientist
58,data scientist,$54K-$93K (Glassdoor est.),4.1,ClearOne Advantage\n4.1,"Baltimore, MD","Baltimore, MD",501 - 1000,2008,Company - Private,Banks & Credit Unions,Finance,Unknown / Non-Applicable,-1,0,0,54,93,73.5,ClearOne Advantage,MD,13,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,data scientist,na,na,Data Scientist
59,data scientist,$71K-$119K (Glassdoor est.),3.4,CyrusOne\n3.4,"Dallas, TX","Dallas, TX",201 - 500,2000,Company - Public,Real Estate,Real Estate,$1 to $2 billion (USD),"Digital Realty, CoreSite, Equinix",0,0,71,119,95.0,CyrusOne,TX,21,1,0,1,1,1,0,0,0,0,0,0,0,1,0,1,0,data scientist,na,na,Data Scientist

In [20]:
# Convert seniority_title to lowercase and remove extra spaces
df['seniority_by_title'].str.lower().str.strip()

0      na
1      na
2      na
3      na
4      na
5      na
6      na
7      na
8      na
9      na
10     na
11     na
12     na
13     na
14     na
15     na
16     na
17     na
18     na
19     na
20     na
21     sr
22     na
23     na
24     na
25     na
26     na
27     na
28     na
29     na
30     na
31     na
32     na
33     na
34     na
35     na
36     na
37     na
38     sr
39     na
40     na
41     na
42     na
43     na
44     sr
45     na
46     sr
47     na
48     na
49     na
50     na
51     na
52     na
53     na
54     na
55     na
56     na
57     na
58     na
59     na
60     sr
61     na
62     sr
63     na
64     na
65     na
66     na
67     na
68     na
69     na
70     na
71     na
72     na
73     sr
74     na
75     sr
76     na
77     na
78     na
79     na
80     na
81     jr
82     na
83     na
84     na
85     na
86     na
87     na
88     na
89     na
90     na
91     sr
92     na
93     na
94     na
95     na
96     na
97     na
98     na
99     sr
100    na
101    na
102    na
103    sr
104    na
105    sr
106    na
107    sr
108    na
109    na
110    na
111    na
112    na
113    na
114    na
115    na
116    na
117    na
118    na
119    sr
120    na
121    na
122    na
123    na
124    na
125    na
126    na
127    na
128    sr
129    na
130    sr
131    na
132    na
133    na
134    na
135    na
136    na
137    na
138    na
139    na
140    sr
141    na
142    na
143    sr
144    na
145    na
146    na
147    sr
148    na
149    sr
150    sr
151    sr
152    na
153    na
154    sr
155    sr
156    sr
157    na
158    na
159    na
160    sr
161    na
162    na
163    sr
164    sr
165    na
166    na
167    na
168    sr
169    na
170    na
171    na
172    sr
173    sr
174    sr
175    sr
176    sr
177    na
178    sr
179    sr
180    na
181    na
182    na
183    sr
184    na
185    sr
186    na
187    sr
188    sr
189    na
190    sr
191    na
192    sr
193    na
194    sr
195    sr
196    na
197    na
198    na
199    sr
200    na
201    sr
202    na
203    na
204    na
205    sr
206    na
207    na
208    sr
209    na
210    na
211    na
212    sr
213    na
214    na
215    na
216    na
217    na
218    na
219    sr
220    sr
221    sr
222    na
223    na
224    na
225    na
226    na
227    na
228    na
229    na
230    na
231    na
232    na
233    na
234    sr
235    na
236    na
237    sr
238    na
239    na
240    na
241    na
242    na
243    na
244    sr
245    na
246    na
247    jr
248    na
249    na
250    sr
251    na
252    na
253    na
254    na
255    na
256    sr
257    na
258    na
259    sr
260    na
261    sr
262    sr
263    na
264    na
265    na
266    sr
267    na
268    sr
269    na
270    sr
271    na
272    sr
273    na
274    na
275    na
276    na
277    na
278    na
279    na
280    na
281    sr
282    sr
283    sr
284    na
285    na
286    na
287    na
288    sr
289    na
290    na
291    sr
292    na
293    sr
294    sr
295    na
296    na
297    sr
298    sr
299    na
300    sr
301    na
302    na
303    na
304    sr
305    na
306    na
307    na
308    na
309    na
310    sr
311    na
312    sr
313    sr
314    na
315    na
316    na
317    na
318    na
319    na
320    sr
321    na
322    na
323    sr
324    na
325    na
326    na
327    na
328    na
329    na
330    sr
331    na
332    na
333    na
334    na
335    na
336    sr
337    na
338    na
339    na
340    na
341    na
342    na
343    sr
344    sr
345    na
346    na
347    sr
348    na
349    sr
350    na
351    na
352    sr
353    na
354    na
355    na
356    na
357    na
358    na
359    na
360    sr
361    sr
362    sr
363    na
364    sr
365    na
366    na
367    na
368    sr
369    na
370    na
371    na
372    na
373    na
374    na
375    sr
376    na
377    sr
378    na
379    sr
380    sr
381    na
382    na
383    na
384    sr
385    na
386    sr
387    na
388    na
389    sr
390    na
391    na
392    na
393    na
394    sr
395    sr
396    na
397    sr
398    na
399    sr
400    sr
401    sr
402    na
403    na
404    sr
405    sr
406    sr
407    sr
408    na
409    sr
410    na
411    sr
412    na
413    sr
414    na
415    sr
416    na
417    sr
418    sr
419    sr
420    na
421    sr
422    na
423    na
424    na
425    na
426    na
427    sr
428    na
429    sr
430    na
431    na
432    sr
433    na
434    na
435    na
436    na
437    na
438    na
439    sr
440    na
441    na
442    na
443    na
444    na
445    na
446    na
447    na
448    na
449    na
450    sr
451    na
452    na
453    na
454    na
455    na
456    na
457    na
458    na
459    na
460    na
461    na
462    na
463    na
464    na
465    na
466    sr
467    sr
468    na
469    na
470    na
471    na
472    na
473    sr
474    sr
475    na
476    sr
477    na
478    na
479    na
480    na
481    na
482    na
483    na
484    na
485    sr
486    na
487    sr
488    sr
489    na
490    na
491    na
492    na
493    na
494    sr
495    na
496    na
497    na
498    sr
499    na
500    na
501    na
502    na
503    na
504    sr
505    na
506    sr
507    sr
508    na
509    na
510    na
511    na
512    na
513    na
514    sr
515    na
516    sr
517    na
518    na
519    sr
520    sr
521    na
522    sr
523    na
524    na
525    sr
526    na
527    sr
528    na
529    na
530    sr
531    na
532    na
533    na
534    na
535    na
536    na
537    sr
538    na
539    na
540    sr
541    sr
542    na
543    sr
544    na
545    na
546    na
547    sr
548    na
549    na
550    na
551    na
552    sr
553    sr
554    na
555    sr
556    sr
557    na
558    na
559    na
560    na
561    na
562    na
563    na
564    na
565    sr
566    na
567    sr
568    sr
569    sr
570    sr
571    na
572    na
573    na
574    na
575    na
576    na
577    sr
578    sr
579    sr
580    na
581    na
582    sr
583    na
584    na
585    sr
586    na
587    na
588    na
589    na
590    sr
591    na
592    na
593    sr
594    na
595    na
596    na
597    na
598    na
599    na
600    sr
601    na
602    sr
603    sr
604    na
605    sr
606    na
607    na
608    na
609    sr
610    sr
611    sr
612    sr
613    na
614    sr
615    na
616    na
617    na
618    sr
619    sr
620    na
621    sr
622    sr
623    na
624    sr
625    na
626    sr
627    na
628    na
629    sr
630    sr
631    sr
632    sr
633    sr
634    na
635    na
636    sr
637    sr
638    na
639    na
640    sr
641    sr
642    sr
643    sr
644    na
645    na
646    na
647    na
648    na
649    sr
650    sr
651    na
652    na
653    na
654    na
655    na
656    na
657    na
658    na
659    na
660    na
661    sr
662    sr
663    na
664    na
665    na
666    na
667    sr
668    na
669    na
670    sr
671    na
672    sr
673    sr
674    na
675    na
676    na
677    na
678    na
679    sr
680    sr
681    sr
682    na
683    na
684    na
685    na
686    na
687    na
688    na
689    na
690    na
691    sr
692    jr
693    sr
694    na
695    na
696    na
697    sr
698    na
699    sr
700    na
701    sr
702    sr
703    na
704    na
705    sr
706    na
707    sr
708    na
709    na
710    sr
711    na
712    na
713    na
714    na
715    na
716    sr
717    na
718    sr
719    na
720    na
721    na
722    sr
723    sr
724    na
725    sr
726    na
727    na
728    sr
729    na
730    na
731    na
732    na
733    sr
734    na
735    na
736    sr
737    sr
738    sr
739    na
740    na
741    na
Name: seniority_by_title, dtype: object

In [21]:
# Standardize seniority_title into meaningful title
df['Seniority_Title'] = df['seniority_by_title'].replace({
    'jr': 'Junior',
    'sr': 'Senior',
    'na': 'Not Specified'
})

In [22]:
# Count the number of Seniority_title
df['Seniority_Title'].value_counts()

Seniority_Title
Not Specified    519
Senior           220
Junior             3
Name: count, dtype: int64

In [23]:
# Convert Degree column to string, remove extra spaces and lowercase with meaningful Degree name
df['Degree'] = df['Degree'].astype(str).str.strip().str.lower()

df['Degree_Required'] = df['Degree'].replace({
    'm': 'Masters',
    'p': 'PhD',
    'na': 'Not_Specified'
})

In [24]:
# Count the number of Degree
df['Degree_Required'].value_counts()

Degree_Required
Not_Specified    383
Masters          252
PhD              107
Name: count, dtype: int64

In [25]:
df.head(51)

,Job_Title,Salary_Estimate,Rating,Company_Name,Location,Headquarters,Size,Founded,Type_of_ownership,Industry,Sector,Revenue,Competitors,Hourly,Employer_provided,Lower_Salary,Upper_Salary,Avg_SalaryK,company_txt,Job_Location,Age,Python,spark,aws,excel,sql_,sas,keras,pytorch,scikit,tensor,hadoop,tableau,bi,flink,mongo,google_an,job_title_sim,seniority_by_title,Degree,Job_Category,Seniority_Title,Degree_Required
0,data scientist,$53K-$91K (Glassdoor est.),3.8,Tecolote Research\n3.8,"Albuquerque, NM","Goleta, CA",501 - 1000,1973,Company - Private,Aerospace & Defense,Aerospace & Defense,$50 to $100 million (USD),-1,0,0,53,91,72.0,Tecolote Research,NM,48,1,0,0,1,0,1,0,0,0,0,0,1,1,0,0,0,data scientist,na,m,Data Scientist,Not Specified,Masters
1,healthcare data scientist,$63K-$112K (Glassdoor est.),3.4,University of Maryland Medical System\n3.4,"Linthicum, MD","Baltimore, MD",10000+,1984,Other Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1,0,0,63,112,87.5,University of Maryland Medical System,MD,37,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,data scientist,na,m,Data Scientist,Not Specified,Masters
2,data scientist,$80K-$90K (Glassdoor est.),4.8,KnowBe4\n4.8,"Clearwater, FL","Clearwater, FL",501 - 1000,2010,Company - Private,Security Services,Business Services,$100 to $500 million (USD),-1,0,0,80,90,85.0,KnowBe4,FL,11,1,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,data scientist,na,m,Data Scientist,Not Specified,Masters
3,data scientist,$56K-$97K (Glassdoor est.),3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 - 5000,1965,Government,Energy,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa...",0,0,56,97,76.5,PNNL,WA,56,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,data scientist,na,na,Data Scientist,Not Specified,Not_Specified
4,data scientist,$86K-$143K (Glassdoor est.),2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 - 200,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee",0,0,86,143,114.5,Affinity Solutions,NY,23,1,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,data scientist,na,na,Data Scientist,Not Specified,Not_Specified
5,data scientist,$71K-$119K (Glassdoor est.),3.4,CyrusOne\n3.4,"Dallas, TX","Dallas, TX",201 - 500,2000,Company - Public,Real Estate,Real Estate,$1 to $2 billion (USD),"Digital Realty, CoreSite, Equinix",0,0,71,119,95.0,CyrusOne,TX,21,1,0,1,1,1,0,0,0,0,0,0,0,1,0,1,0,data scientist,na,na,Data Scientist,Not Specified,Not_Specified
6,data scientist,$54K-$93K (Glassdoor est.),4.1,ClearOne Advantage\n4.1,"Baltimore, MD","Baltimore, MD",501 - 1000,2008,Company - Private,Banks & Credit Unions,Finance,Unknown / Non-Applicable,-1,0,0,54,93,73.5,ClearOne Advantage,MD,13,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,data scientist,na,na,Data Scientist,Not Specified,Not_Specified
7,data scientist,$86K-$142K (Glassdoor est.),3.8,Logic20/20\n3.8,"San Jose, CA","Seattle, WA",201 - 500,2005,Company - Private,Consulting,Business Services,$25 to $50 million (USD),-1,0,0,86,142,114.0,Logic20/20,CA,16,1,1,1,1,1,0,0,1,0,1,0,0,0,0,0,0,data scientist,na,m,Data Scientist,Not Specified,Masters
8,research scientist,$38K-$84K (Glassdoor est.),3.3,Rochester Regional Health\n3.3,"Rochester, NY","Rochester, NY",10000+,2014,Hospital,Health Care Services & Hospitals,Health Care,$500 million to $1 billion (USD),-1,0,0,38,84,61.0,Rochester Regional Health,NY,7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,other scientist,na,p,Other Scientist,Not Specified,PhD
9,data scientist,$120K-$160K (Glassdoor est.),4.6,<intent>\n4.6,"New York, NY","New York, NY",51 - 200,2009,Company - Private,Internet,Information Technology,$100 to $500 million (USD),"Clicktripz, SmarterTravel",0,0,120,160,140.0,<intent>,NY,12,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,data scientist,na,na,Data Scientist,Not Specified,Not_Specified
10,data scientist,$126K-$201K (Glassdoor est.),3.5,Wish\n3.5,"San Jose, CA","San Francisco, CA",501 - 1000,2011,Company - Private,Other Retail Stores,Retail,$1 to $2 billion (USD),-1,0,0,126,201,163.5,Wish,CA,10,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,data scientist,na,na,Data Scientist,Not Specified,Not_Specified
11,data scientist,$64K-$106K (Glassdoor est.),4.1,ManTech\n4.1,"Chantilly, VA","Herndon, VA",5001 - 10000,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1,0,0,64,106,85.0,ManTech,VA,53,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,data scientist,na,na,Data Scientist,Not Specified,Not_Specified
12,staff data scientist technology,$106K-$172K (Glassdoor est.),3.2,Walmart\n3.2,"Plano, TX","Bentonville, AR",10000+,1962,Company - Public,"Department, Clothing, & Shoe Stores",Retail,$10+ billion (USD),"Target, Costco Wholesale, Amazon",0,0,106,172,139.0,Walmart,TX,59,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,data scientist,na,m,Data Scientist,Not Specified,Masters
13,data analyst,$46K-$85K (Glassdoor est.),4.1,Yesler\n4.1,"Seattle, WA","Seattle, WA",201 - 500,2012,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,-1,0,0,46,85,65.5,Yesler,WA,9,1,1,1,1,1,0,0,0,0,0,0,1,1,0,0,0,analyst,na,na,Data Analyst,Not Specified,Not_Specified
14,data scientist,$83K-$144K (Glassdoor est.),3.7,Takeda Pharmaceuticals\n3.7,"Cambridge, MA","OSAKA, Japan",10000+,1781,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),"Novartis, Baxter, Pfizer",0,0,83,144,113.5,Takeda Pharmaceuticals,MA,240,1,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,data scientist,na,m,Data Scientist,Not Specified,Masters
15,data engineer i,$102K-$190K (Glassdoor est.),3.6,Audible\n3.6,"Newark, NJ","Newark, NJ",1001 - 5000,1995,Subsidiary or Business Segment,Motion Picture Production & Distribution,Media,Unknown / Non-Applicable,-1,0,0,102,190,146.0,Audible,NJ,26,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,data engineer,na,na,Data Engineer,Not Specified,Not_Specified
16,scientist i ii biology,$67K-$137K (Glassdoor est.),3.9,Blueprint Medicines\n3.9,"Cambridge, MA","Cambridge, MA",51 - 200,2011,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$1 to $5 million (USD),"bluebird bio, Agios Pharmaceuticals, Celgene",0,0,67,137,102.0,Blueprint Medicines,MA,10,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,other scientist,na,p,Other Scientist,Not Specified,PhD
17,customer data scientist,$118K-$189K (Glassdoor est.),4.3,h2o.ai\n4.3,"Mountain View, CA","Mountain View, CA",201 - 500,2011,Company - Private,Enterprise Software & Network Solutions,Information Technology,Unknown / Non-Applicable,-1,0,0,118,189,153.5,h2o.ai,CA,10,1,1,1,1,0,0,0,0,0,0,1,0,0,0,0,0,data scientist,na,m,Data Scientist,Not Specified,Masters
18,data scientist health data analytics,$110K-$175K (Glassdoor est.),4.2,Nuna\n4.2,"San Francisco, CA","San Francisco, CA",51 - 200,2010,Company - Private,Enterprise Software & Network Solutions,Information Technology,Unknown / Non-Applicable,-1,0,0,110,175,142.5,Nuna,CA,11,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,data scientist,na,na,Data Scientist,Not Specified,Not_Specified
19,data scientist,$64K-$111K (Glassdoor est.),4.0,Pinnacol Assurance\n4.0,"Denver, CO","Denver, CO",501 - 1000,1915,Nonprofit Organization,Insurance Carriers,Insurance,$500 million to $1 billion (USD),-1,0,0,64,111,87.5,Pinnacol Assurance,CO,106,1,0,0,1,1,0,1,1,1,1,0,0,0,0,0,0,data scientist,na,m,Data Scientist,Not Specified,Masters
20,data scientist,$81K-$130K (Glassdoor est.),3.2,Porch\n3.2,"Seattle, WA","Seattle, WA",201 - 500,2012,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,"Angie's List, HomeAdvisor, Thumbtack",0,0,81,130,105.5,Porch,WA,9,1,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,data scientist,na,m,Data Scientist,Not Specified,Masters
21,senior data scientist machine learning,$73K-$119K (Glassdoor est.),3.9,Health IQ\n3.9,"Dallas, TX","Mountain View, CA",201 - 500,2013,Company - Private,Insurance Agencies & Brokerages,Insurance,Unknown / Non-Applicable,-1,0,0,73,119,96.0,Health IQ,TX,8,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,data scientist,sr,p,Data Scientist,Senior,PhD
22,data scientist quantitative,$86K-$139K (Glassdoor est.),3.8,Truckstop.com\n3.8,"Chicago, IL","New Plymouth, ID",501 - 1000,1995,Company - Private,Logistics & Supply Chain,Transportation & Logistics,Unknown / Non-Applicable,-1,0,0,86,139,112.5,Truckstop.com,IL,26,1,0,1,1,1,0,0,0,0,0,0,0,0,0,1,0,data scientist,na,m,Data Scientist,Not Specified,Masters
23,data scientist,$63K-$105K (Glassdoor est.),4.3,SMC 3\n4.3,"Louisville, KY","Peachtree City, GA",51 - 200,1935,Nonprofit Organization,Logistics & Supply Chain,Transportation & Logistics,$10 to $25 million (USD),-1,0,0,63,105,84.0,SMC 3,KY,86,1,0,0,1,1,0,0,0,0,0,0,1,0,0,0,0,data scientist,na,m,Data Scientist,Not Specified,Masters
24,data scientist,$109K-$177K (Glassdoor est.),4.0,Novetta\n4.0,"Herndon, VA","Mc Lean, VA",501 - 1000,2012,Company - Private,Enterprise Software & Network Solutions,Information Technology,$100 to $500 million (USD),"Leidos, CACI International, Booz Allen Hamilton",0,0,109,177,143.0,Novetta,VA,9,1,0,1,0,0,0,1,0,0,1,0,0,0,0,0,0,data scientist,na,na,Data Scientist,Not Specified,Not_Specified
25,digital health data scientist,$63K-$110K (Glassdoor est.),4.0,Pfizer\n4.0,"Cambridge, MA","New York, NY",10000+,1849,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),-1,0,0,63,110,86.5,Pfizer,MA,172,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,data scientist,na,na,Data Scientist,Not Specified,Not_Specified
26,data scientist,$75K-$124K (Glassdoor est.),3.5,First Tech Federal Credit Union\n3.5,"Hillsboro, OR","San Jose, CA",1001 - 5000,1952,Company - Private,Banks & Credit Unions,Finance,$100 to $500 million (USD),-1,0,0,75,124,99.5,First Tech Federal Credit Union,OR,69,1,1,1,1,1,0,1,0,1,1,0,1,0,0,0,0,data scientist,na,na,Data Scientist,Not Specified,Not_Specified
27,associate data analyst,$34K-$61K (Glassdoor est.),3.7,The Hanover Insurance Group\n3.7,"Worcester, MA","Worcester, MA",5001 - 10000,1852,Company - Public,Insurance Carriers,Insurance,$5 to $10 billion (USD),-1,0,0,34,61,47.5,The Hanover Insurance Group,MA,169,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,analyst,na,na,Data Analyst,Not Specified,Not_Specified
28,clinical data scientist,$63K-$105K (Glassdoor est.),4.0,Pfizer\n4.0,"Groton, CT","New York, NY",10000+,1849,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),-1,0,0,63,105,84.0,Pfizer,CT,172,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,data scientist,na,m,Data Scientist,Not Specified,Masters
29,data scientist,$80K-$90K (Glassdoor est.),4.8,KnowBe4\n4.8,"Clearwater, FL","Clearwater, FL",501 - 1000,2010,Company - Private,Security Services,Business Services,$100 to $500 million (USD),-1,0,0,80,90,85.0,KnowBe4,FL,11,1,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,data scientist,na,m,Data Scientist,Not Specified,Masters
30,data scientist,$56K-$97K (Glassdoor est.),3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 - 5000,1965,Government,Energy,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa...",0,0,56,97,76.5,PNNL,WA,56,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,data scientist,na,na,Data Scientist,Not Specified,Not_Specified
31,data scientist,$72K-$120K (Glassdoor est.),3.6,Amrock\n3.6,"Detroit, MI","Detroit, MI",1001 - 5000,1997,Company - Private,Real Estate,Real Estate,$500 million to $1 billion (USD),-1,0,0,72,120,96.0,Amrock,MI,24,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,data scientist,na,m,Data Scientist,Not Specified,Masters
32,data scientist machine learning expert,$86K-$143K (Glassdoor est.),3.8,Novartis\n3.8,"Cambridge, MA","Basel, Switzerland",10000+,1996,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),-1,0,0,86,143,114.5,Novartis,MA,25,1,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,data scientist,na,na,Data Scientist,Not Specified,Not_Specified
33,data scientist,$93K-$149K (Glassdoor est.),3.8,Juniper Networks\n3.8,"Sunnyvale, CA","Sunnyvale, CA",5001 - 10000,1996,Company - Public,Telecommunications Services,Telecommunications,$2 to $5 billion (USD),-1,0,0,93,149,121.0,Juniper Networks,CA,25,1,1,0,1,1,0,1,0,1,1,0,0,0,0,1,0,data scientist,na,m,Data Scientist,Not Specified,Masters
34,data scientist,$85K-$140K (Glassdoor est.),4.7,New England Biolabs\n4.7,"Ipswich, MA","Ipswich, MA",201 - 500,1974,Company - Private,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable,"Thermo Fisher Scientific, Enzymatics, Illumina",0,0,85,140,112.5,New England Biolabs,MA,47,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,data scientist,na,na,Data Scientist,Not Specified,Not_Specified
35,web data analyst,$77K-$135K (Glassdoor est.),4.2,Clarity Insights\n4.2,"San Jose, CA","Chicago, IL",201 - 500,2008,Company - Private,IT Services,Information Technology,Unknown / Non-Applicable,-1,0,0,77,135,106.0,Clarity Insights,CA,13,1,0,0,1,1,0,0,0,0,0,0,1,1,0,0,0,analyst,na,na,Data Analyst,Not Specified,Not_Specified
36,data scientist,$82K-$132K (Glassdoor est.),3.5,Esri\n3.5,"Redlands, CA","Redlands, CA",1001 - 5000,1969,Company - Private,Computer Hardware & Software,Information Technology,$1 to $2 billion (USD),Pitney Bowes,0,0,82,132,107.0,Esri,CA,52,1,1,1,0,0,0,0,0,0,0,1,1,0,0,1,0,data scientist,na,m,Data Scientist,Not Specified,Masters
37,data scientist,$83K-$137K (Glassdoor est.),4.7,Systems & Technology Research\n4.7,"Woburn, MA","Woburn, MA",201 - 500,2010,Company - Private,Aerospace & Defense,Aerospace & Defense,$100 to $500 million (USD),-1,0,0,83,137,110.0,Systems & Technology Research,MA,11,1,1,0,1,1,0,0,1,1,1,1,0,0,0,0,0,data scientist,na,p,Data Scientist,Not Specified,PhD
38,senior data scientist,$115K-$180K (Glassdoor est.),3.5,Sartorius\n3.5,"Fremont, CA","Gottingen, Germany",5001 - 10000,1870,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$1 to $2 billion (USD),-1,0,0,115,180,147.5,Sartorius,CA,151,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,data scientist,sr,m,Data Scientist,Senior,Masters
39,data engineer,$74K-$138K (Glassdoor est.),3.5,Lancer Insurance\n3.5,"Long Beach, NY","Long Beach, NY",201 - 500,1985,Company - Private,Insurance Carriers,Insurance,$100 to $500 million (USD),-1,0,0,74,138,106.0,Lancer Insurance,NY,36,1,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,data engineer,na,m,Data Engineer,Not Specified,Masters
40,data analyst,$64K-$112K (Glassdoor est.),4.2,Sauce Labs\n4.2,"San Francisco, CA","San Francisco, CA",201 - 500,2008,Company - Private,IT Services,Information Technology,$50 to $100 million (USD),"BrowserStack, Selenium Master, Perfecto Mobile",0,0,64,112,88.0,Sauce Labs,CA,13,1,0,1,1,1,0,0,0,0,0,0,1,0,0,1,0,analyst,na,na,Data Analyst,Not Specified,Not_Specified
41,data engineer,$68K-$129K (Glassdoor est.),3.6,Persivia\n3.6,"Marlborough, MA","Lowell, MA",Jan-50,-1,Company - Private,-1,-1,Less than $1 million (USD),-1,0,0,68,129,98.5,Persivia,MA,-1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,data engineer,na,na,Data Engineer,Not Specified,Not_Specified
42,data scientist algorithms inference,$110K-$175K (Glassdoor est.),4.2,Nuna\n4.2,"San Francisco, CA","San Francisco, CA",51 - 200,2010,Company - Private,Enterprise Software & Network Solutions,Information Technology,Unknown / Non-Applicable,-1,0,0,110,175,142.5,Nuna,CA,11,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,data scientist,na,m,Data Scientist,Not Specified,Masters
43,scientist,$52K-$113K (Glassdoor est.),3.4,Edgewell Personal Care\n3.4,"Allendale, NJ","Shelton, CT",5001 - 10000,2015,Company - Public,Consumer Products Manufacturing,Manufacturing,$2 to $5 billion (USD),"Unilever, Procter & Gamble, Henkel",0,0,52,113,82.5,Edgewell Personal Care,NJ,6,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,other scientist,na,m,Other Scientist,Not Specified,Masters
44,senior data scientist,$110K-$150K(Employer est.),4.3,Equity Residential\n4.3,"Chicago, IL","Chicago, IL",1001 - 5000,1993,Company - Public,Real Estate,Real Estate,$2 to $5 billion (USD),"UDR, AvalonBay Communities, Essex Property Trust",0,0,110,150,130.0,Equity Residential,IL,28,1,1,0,1,1,0,0,0,1,0,1,1,1,0,0,0,data scientist,sr,m,Data Scientist,Senior,Masters
45,data scientist,Employer Provided Salary:$150K-$160K,5.0,BPA Services\n5.0,"Washington, DC","Alexandria, VA",unknown,-1,Company - Private,Enterprise Software & Network Solutions,Information Technology,Unknown / Non-Applicable,-1,0,1,150,160,155.0,BPA Services,DC,-1,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,data scientist,na,na,Data Scientist,Not Specified,Not_Specified
46,lead data scientist,$158K-$211K (Glassdoor est.),3.7,Visa Inc.\n3.7,"Bellevue, WA","Foster City, CA",10000+,1958,Company - Public,IT Services,Information Technology,$10+ billion (USD),"American Express, Mastercard, Discover",0,0,158,211,184.5,Visa Inc.,WA,63,1,0,0,1,1,1,0,0,0,0,0,1,0,0,0,0,data scientist,sr,na,Data Scientist,Senior,Not_Specified
47,associate data analyst,$20K-$39K (Glassdoor est.),3.1,Intrado\n3.1,"Longmont, CO","Omaha, NE",5001 - 10000,1986,Company - Private,Enterprise Software & Network Solutions,Information Technology,$2 to $5 billion (USD),-1,0,0,20,39,29.5,Intrado,CO,35,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,analyst,na,m,Data Analyst,Not Specified,Masters
48,spectral scientist engineer,$56K-$117K (Glassdoor est.),4.7,Centauri\n4.7,"Beavercreek, OH","Chantilly, VA",501 - 1000,1999,Company - Private,Aerospace & Defense,Aerospace & Defense,$100 to $500 million (USD),"TASC, Vencore, Booz Allen Hamilton",0,0,56,117,86.5,Centauri,OH,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,other scientist,na,m,Other Scientist,Not Specified,Masters
49,college hire data scientist open to decemb...,$63K-$99K (Glassdoor est.),3.7,Caterpillar\n3.7,"Peoria, IL","Deerfield, IL",10000+,1925,Company - Public,Industrial Manufacturing,Manufacturing,$10+ billion (USD),"John Deere, Komatsu, CNH Industrial",0,0,63,99,81.0,Caterpillar,IL,96,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,data scientist,na,na,Data Scientist,Not Specified,Not_Specified
50,data scientist,$68K-$114K (Glassdoor est.),3.8,Zimmerman Advertising\n3.8,"Fort Lauderdale, FL","Fort Lauderdale, FL",501 - 1000,1984,Subsidiary or Business Segment,Advertising & Marketing,Business Services,Unknown / Non-Applicable,-1,0,0,68,114,91.0,Zimmerman Advertising,FL,37,1,0,0,1,1,0,0,0,0,0,1,1,0,0,0,0,data scientist,na,na,Data Scientist,Not Specified,Not_Specified

In [26]:
# Now Remove old columns
df.drop(['job_title_sim', 'seniority_by_title','Degree'], axis=1, inplace=True)

In [27]:
# To see the Rating Column with count
df['Rating'].value_counts()

Rating
 3.9    63
 3.8    61
 3.7    61
 3.5    49
 4.0    47
 3.6    46
 3.4    44
 3.3    39
 3.2    35
 4.4    33
 4.3    32
 4.7    31
 4.2    26
 3.1    25
 4.1    19
 2.9    18
 3.0    17
 2.7    14
 2.6    12
-1.0    11
 4.6    10
 4.8     9
 2.4     7
 2.8     7
 4.5     7
 2.1     5
 5.0     5
 1.9     3
 2.3     2
 2.5     2
 2.2     2
Name: count, dtype: int64

In [28]:
# Import NumPy library for numerical calculation and handling missing values
import numpy as np

In [29]:
# Replace invalid rating values (-1) with NaN to mark them as missing
df['Rating'].replace(-1, np.nan)

0      3.8
1      3.4
2      4.8
3      3.8
4      2.9
5      3.4
6      4.1
7      3.8
8      3.3
9      4.6
10     3.5
11     4.1
12     3.2
13     4.1
14     3.7
15     3.6
16     3.9
17     4.3
18     4.2
19     4.0
20     3.2
21     3.9
22     3.8
23     4.3
24     4.0
25     4.0
26     3.5
27     3.7
28     4.0
29     4.8
30     3.8
31     3.6
32     3.8
33     3.8
34     4.7
35     4.2
36     3.5
37     4.7
38     3.5
39     3.5
40     4.2
41     3.6
42     4.2
43     3.4
44     4.3
45     5.0
46     3.7
47     3.1
48     4.7
49     3.7
50     3.8
51     3.3
52     4.6
53     3.7
54     3.7
55     3.5
56     4.1
57     4.7
58     4.1
59     3.4
60     4.4
61     4.3
62     3.8
63     3.8
64     3.8
65     2.8
66     4.7
67     3.1
68     3.2
69     4.0
70     4.4
71     3.6
72     2.7
73     3.9
74     3.1
75     4.0
76     4.3
77     1.9
78     3.3
79     4.4
80     3.9
81     4.7
82     4.5
83     4.3
84     4.0
85     4.4
86     3.2
87     3.8
88     4.2
89     4.5
90     3.5
91     3.5
92     3.9
93     4.7
94     4.2
95     3.4
96     3.2
97     3.9
98     3.1
99     4.1
100    3.8
101    4.7
102    4.3
103    4.2
104    3.9
105    3.3
106    4.7
107    4.3
108    2.9
109    4.5
110    3.4
111    3.7
112    4.6
113    3.2
114    4.0
115    4.6
116    2.8
117    4.7
118    3.0
119    3.2
120    4.4
121    3.5
122    4.0
123    4.3
124    2.3
125    4.0
126    3.6
127    3.8
128    3.7
129    4.4
130    4.0
131    3.2
132    2.9
133    3.8
134    4.3
135    3.4
136    4.1
137    4.3
138    5.0
139    4.3
140    3.7
141    4.2
142    4.3
143    2.6
144    3.8
145    3.9
146    4.3
147    3.8
148    3.8
149    3.8
150    4.8
151    4.4
152    3.9
153    3.4
154    3.6
155    3.9
156    3.8
157    3.7
158    3.8
159    3.5
160    3.9
161    4.2
162    4.2
163    3.5
164    2.9
165    3.6
166    2.7
167    4.4
168    4.0
169    4.3
170    4.2
171    3.6
172    3.7
173    2.8
174    3.7
175    3.3
176    NaN
177    3.6
178    3.7
179    3.4
180    4.1
181    2.6
182    3.2
183    3.9
184    4.7
185    3.7
186    2.9
187    3.0
188    4.7
189    3.7
190    3.3
191    4.0
192    4.4
193    3.9
194    3.3
195    4.1
196    3.6
197    4.0
198    2.4
199    2.6
200    3.5
201    3.0
202    3.6
203    3.3
204    2.7
205    3.4
206    3.8
207    3.7
208    4.8
209    3.8
210    3.4
211    4.3
212    4.8
213    3.4
214    3.9
215    3.4
216    3.1
217    3.2
218    4.3
219    3.6
220    3.9
221    3.8
222    2.8
223    3.7
224    3.4
225    4.0
226    3.5
227    3.8
228    3.7
229    3.5
230    4.2
231    4.0
232    4.3
233    4.7
234    3.5
235    4.4
236    4.1
237    2.9
238    2.5
239    4.2
240    3.9
241    4.3
242    2.7
243    3.9
244    3.4
245    3.8
246    3.6
247    3.3
248    3.4
249    3.0
250    4.0
251    3.7
252    4.4
253    4.3
254    4.0
255    4.0
256    3.2
257    4.2
258    3.9
259    3.7
260    3.6
261    3.7
262    2.8
263    4.2
264    4.0
265    3.5
266    NaN
267    3.2
268    3.3
269    3.9
270    3.7
271    3.6
272    3.4
273    3.5
274    4.3
275    4.1
276    2.6
277    3.6
278    3.5
279    3.6
280    2.3
281    3.9
282    4.0
283    4.1
284    3.2
285    4.7
286    4.2
287    4.6
288    3.7
289    3.7
290    4.4
291    3.7
292    3.9
293    3.6
294    3.0
295    3.4
296    4.1
297    3.8
298    4.0
299    3.9
300    NaN
301    4.4
302    3.8
303    3.8
304    2.2
305    2.9
306    4.1
307    3.7
308    3.8
309    3.6
310    4.7
311    3.5
312    3.3
313    4.4
314    3.3
315    3.4
316    4.0
317    4.4
318    3.8
319    3.5
320    3.5
321    2.9
322    3.9
323    3.3
324    3.7
325    3.6
326    3.5
327    4.7
328    3.9
329    3.7
330    4.1
331    3.1
332    3.6
333    3.0
334    3.5
335    3.6
336    3.5
337    4.0
338    3.7
339    2.4
340    3.2
341    2.1
342    3.7
343    2.6
344    4.4
345    3.7
346    3.5
347    3.0
348    4.2
349    3.9
350    4.0
351    3.3
352    4.4
353    3.4
354    3.3
355    2.9
356    2.7
357    3.6
358    3.1
359    3.3
360    4.5
361    3.9
362    3.2
363    3.3
364    3.1
365    2.4
366    4.8
367    2.9
368    2.9
369    3.4
370    NaN
371    2.6
372    3.8
373    5.0
374    3.6
375    4.0
376    3.8
377    3.9
378    3.8
379    4.3
380    1.9
381    3.3
382    4.7
383    3.1
384    3.4
385    4.4
386    3.9
387    3.9
388    4.7
389    4.7
390    3.4
391    3.8
392    2.7
393    3.1
394    3.4
395    4.0
396    3.5
397    3.4
398    3.7
399    4.3
400    3.7
401    3.8
402    4.6
403    4.4
404    NaN
405    3.0
406    4.7
407    3.8
408    3.2
409    2.7
410    3.3
411    3.9
412    3.7
413    3.1
414    3.7
415    4.3
416    3.6
417    2.1
418    3.9
419    3.9
420    3.8
421    3.1
422    3.5
423    4.7
424    5.0
425    3.6
426    3.8
427    4.7
428    3.6
429    4.7
430    3.5
431    3.5
432    3.3
433    2.7
434    3.4
435    4.7
436    2.8
437    3.5
438    3.2
439    4.4
440    3.3
441    4.0
442    3.4
443    3.8
444    3.5
445    4.4
446    3.7
447    4.7
448    4.1
449    4.0
450    3.5
451    2.5
452    3.9
453    3.4
454    3.6
455    3.5
456    NaN
457    2.9
458    3.5
459    4.8
460    4.0
461    4.2
462    3.8
463    3.7
464    3.9
465    4.6
466    4.3
467    3.3
468    3.7
469    4.0
470    3.6
471    3.9
472    3.7
473    3.7
474    3.9
475    3.7
476    4.1
477    3.1
478    3.1
479    3.0
480    3.6
481    3.6
482    3.5
483    4.2
484    4.0
485    3.9
486    3.7
487    4.4
488    3.5
489    3.7
490    3.6
491    3.4
492    4.0
493    2.4
494    3.7
495    3.5
496    4.4
497    3.3
498    3.9
499    3.2
500    3.2
501    2.1
502    4.0
503    3.7
504    2.6
505    3.4
506    4.4
507    3.2
508    3.5
509    3.7
510    4.2
511    4.2
512    3.1
513    3.9
514    4.3
515    3.3
516    3.9
517    3.5
518    4.0
519    3.9
520    3.0
521    3.7
522    3.5
523    4.0
524    3.3
525    3.2
526    3.4
527    4.4
528    3.3
529    3.2
530    3.8
531    2.9
532    2.7
533    3.6
534    3.1
535    3.3
536    3.7
537    4.5
538    3.0
539    3.8
540    3.9
541    3.2
542    3.3
543    3.1
544    2.4
545    2.9
546    4.8
547    2.9
548    4.7
549    4.7
550    3.4
551    NaN
552    3.9
553    3.6
554    3.6
555    3.9
556    4.4
557    2.6
558    3.6
559    3.2
560    4.2
561    3.6
562    3.1
563    3.8
564    3.8
565    4.0
566    3.8
567    4.0
568    1.9
569    4.0
570    4.3
571    3.6
572    3.3
573    3.8
574    4.3
575    3.2
576    4.7
577    3.4
578    3.8
579    4.5
580    3.1
581    NaN
582    3.9
583    4.4
584    3.4
585    3.9
586    4.7
587    3.3
588    3.9
589    3.4
590    4.7
591    2.7
592    3.8
593    3.4
594    3.8
595    3.9
596    3.1
597    4.1
598    3.7
599    2.8
600    4.0
601    3.5
602    3.4
603    3.7
604    3.0
605    3.8
606    4.6
607    4.4
608    4.0
609    NaN
610    3.0
611    3.0
612    4.7
613    4.2
614    3.8
615    3.5
616    3.3
617    3.2
618    2.7
619    3.3
620    3.7
621    3.9
622    3.1
623    3.7
624    4.3
625    3.8
626    3.9
627    3.6
628    3.7
629    2.1
630    3.9
631    3.9
632    3.2
633    4.6
634    3.8
635    2.2
636    3.1
637    4.6
638    2.6
639    3.4
640    3.3
641    NaN
642    3.7
643    3.5
644    2.7
645    3.8
646    3.7
647    3.8
648    3.3
649    2.7
650    3.8
651    3.8
652    3.0
653    3.9
654    3.6
655    3.5
656    3.6
657    4.2
658    3.5
659    4.0
660    3.7
661    4.4
662    3.5
663    3.6
664    3.7
665    3.4
666    4.0
667    3.7
668    2.4
669    3.5
670    3.9
671    3.2
672    4.4
673    3.9
674    3.4
675    2.1
676    3.7
677    3.4
678    4.0
679    4.4
680    2.6
681    3.2
682    3.7
683    4.2
684    3.5
685    4.3
686    2.6
687    4.2
688    3.1
689    3.8
690    3.9
691    4.3
692    3.2
693    5.0
694    3.3
695    4.3
696    3.5
697    3.9
698    4.0
699    3.9
700    3.4
701    3.0
702    3.9
703    4.0
704    3.3
705    3.2
706    3.4
707    4.4
708    3.3
709    3.2
710    3.8
711    3.6
712    2.9
713    2.7
714    3.2
715    3.1
716    4.0
717    3.3
718    4.5
719    3.0
720    3.7
721    3.8
722    3.9
723    3.2
724    3.3
725    3.1
726    2.4
727    4.8
728    2.9
729    2.9
730    NaN
731    3.4
732    4.1
733    3.9
734    3.6
735    3.9
736    3.6
737    3.9
738    4.4
739    2.6
740    3.2
741    3.6
Name: Rating, dtype: float64

In [30]:
# Create a new column 'Company_Rating' by filling missing Rating values with the median
df['Company_Rating'] = df['Rating'].fillna(df['Rating'].median())

In [31]:
# To see all unique company names in the dataset
list(df['Company_Name'].unique())

['Tecolote Research\n3.8',
 'University of Maryland Medical System\n3.4',
 'KnowBe4\n4.8',
 'PNNL\n3.8',
 'Affinity Solutions\n2.9',
 'CyrusOne\n3.4',
 'ClearOne Advantage\n4.1',
 'Logic20/20\n3.8',
 'Rochester Regional Health\n3.3',
 '<intent>\n4.6',
 'Wish\n3.5',
 'ManTech\n4.1',
 'Walmart\n3.2',
 'Yesler\n4.1',
 'Takeda Pharmaceuticals\n3.7',
 'Audible\n3.6',
 'Blueprint Medicines\n3.9',
 'h2o.ai\n4.3',
 'Nuna\n4.2',
 'Pinnacol Assurance\n4.0',
 'Porch\n3.2',
 'Health IQ\n3.9',
 'Truckstop.com\n3.8',
 'SMC 3\n4.3',
 'Novetta\n4.0',
 'Pfizer\n4.0',
 'First Tech Federal Credit Union\n3.5',
 'The Hanover Insurance Group\n3.7',
 'Amrock\n3.6',
 'Novartis\n3.8',
 'Juniper Networks\n3.8',
 'New England Biolabs\n4.7',
 'Clarity Insights\n4.2',
 'Esri\n3.5',
 'Systems & Technology Research\n4.7',
 'Sartorius\n3.5',
 'Lancer Insurance\n3.5',
 'Sauce Labs\n4.2',
 'Persivia\n3.6',
 'Edgewell Personal Care\n3.4',
 'Equity Residential\n4.3',
 'BPA Services\n5.0',
 'Visa Inc.\n3.7',
 'Intrado\n3.1',
 'Centauri\n4.7',
 'Caterpillar\n3.7',
 'Zimmerman Advertising\n3.8',
 'Liberty Mutual Insurance\n3.3',
 'Torch Technologies, Inc.\n4.6',
 'Swiss Re\n3.7',
 'Northrop Grumman\n3.7',
 'Netskope\n4.1',
 '1904labs\n4.7',
 'The David J. Joseph Company\n4.4',
 'USEReady\n4.3',
 'Bill.com\n3.8',
 'Pacific Northwest National Laboratory\n3.8',
 "DICK'S Sporting Goods - Corporate\n3.8",
 'Berg Health\n2.8',
 'Oversight Systems\n4.7',
 'C Space\n3.1',
 'Numeric, LLC\n3.2',
 'HP Inc.\n4.0',
 'SpringML\n4.4',
 'Grainger\n3.6',
 'EAG Laboratories\n2.7',
 'The Buffalo Group\n3.9',
 'Carmeuse\n3.1',
 'GNS Healthcare\n1.9',
 'Peraton\n3.3',
 'Pactera\n4.4',
 'Nurx\n3.9',
 'webfx.com\n4.7',
 'Johns Hopkins University Applied Physics Laboratory\n4.5',
 'Productive Edge\n4.3',
 'Excella Consulting\n4.0',
 'Gensco\n4.4',
 'goTRG\n4.2',
 'NMR Consulting\n4.5',
 'iSeatz\n3.5',
 'Nektar Therapeutics\n3.5',
 'TransUnion\n3.9',
 'IT Concepts\n4.7',
 'Scientific Research Corporation\n4.2',
 'General Dynamics Information Technology\n3.4',
 'MITRE\n3.2',
 'DentaQuest\n3.1',
 'Redjack\n4.1',
 '7Park Data\n3.8',
 'Rapid Response Monitoring\n4.7',
 'Trilogy Ed\n4.3',
 'Gallup\n4.2',
 'CapTech\n3.9',
 'American Axle & Manufacturing\n3.3',
 'CentralReach\n4.7',
 'Integrate\n4.3',
 'Boys Town Hospital\n2.9',
 'Demandbase\n4.5',
 'Sapphire Digital\n3.4',
 'Formation\n3.2',
 'Autodesk\n4.0',
 "Beck's Hybrids\n4.6",
 'DrFirst\n2.8',
 'Object Partners\n4.7',
 'L.A. Care Health Plan\n3.0',
 'Red Ventures\n3.2',
 'Quick Base\n4.4',
 'The E.W. Scripps Company\n3.5',
 'Upside Business Travel\n4.0',
 'Synagro\n2.3',
 'Alliance Source Testing\n4.0',
 'Accuride International\n3.6',
 'Full Potential Solutions\n3.8',
 'Maven Wave Partners\n4.4',
 'First Command Financial Services, Inc.\n3.2',
 'Pharmavite\n2.9',
 'BioMarin Pharmaceutical\n3.8',
 'Stratagem Group\n4.3',
 'PA Consulting\n3.4',
 'Gridiron IT\n5.0',
 'Evolve Vacation Rental\n3.7',
 'The Church of Jesus Christ of Latter-day Saints\n4.2',
 'Maximus Real Estate Partners\n4.3',
 'Software Engineering Institute\n2.6',
 'AVANADE\n3.9',
 'PatientPoint\n3.8',
 'BlueCross BlueShield of Tennessee\n3.8',
 'KSM Consulting\n4.4',
 'Cogo Labs\n3.9',
 'Church & Dwight\n3.4',
 'MassMutual\n3.6',
 'Genentech\n3.9',
 'Legal & General America\n3.8',
 'Western Digital\n3.5',
 'Sunovion\n3.5',
 'National Student Clearinghouse\n2.9',
 'Tower Health\n3.6',
 'State of Wisconsin Investment Board\n2.7',
 'Rubius Therapeutics\n4.4',
 'OneMagnify\n4.3',
 'IZEA\n4.2',
 'Vionic Group\n3.6',
 'Dodge Data & Analytics\n2.8',
 'Plymouth Rock Assurance\n3.3',
 'CA-One Tech Cloud',
 'Beebe Healthcare\n3.6',
 'Argo Group US\n3.4',
 'Associated Electric Cooperative\n4.1',
 'PennyMac\n3.2',
 'Zest AI\n3.9',
 'DECISIVE ANALYTICS Corporation\n4.7',
 'Karyopharm Therapeutics Inc.\n2.9',
 'Tempus Labs\n3.0',
 'Recursion Pharmaceuticals\n4.7',
 'P2 Energy Solutions\n3.7',
 'ClearEdge\n4.0',
 'Tapjoy\n3.9',
 'Credit Sesame\n4.1',
 'San Manuel Casino\n3.6',
 'Texas Health Huguley Hospital\n4.0',
 'Teasdale Latin Foods\n2.4',
 'Central California Alliance for Health\n3.5',
 'Pilot Flying J Travel Centers LLC\n3.0',
 "Palermo's Pizza\n3.3",
 'Advanced BioScience Laboratories\n2.7',
 'Echo Global Logistics\n3.4',
 'Lockheed Martin\n3.7',
 'Acuity Insurance\n4.8',
 'Fareportal\n3.8',
 'Veterans Affairs, Veterans Health Administration\n3.4',
 'Credera\n4.3',
 'Spectrum Communications and Consulting\n3.4',
 'NCSOFT\n3.1',
 'Dayton Freight Lines, Inc.\n4.3',
 'Community Action Partnership of San Luis Obispo\n2.8',
 'TrueAccord\n3.4',
 'DRB Systems\n4.0',
 'Corcentric\n3.7',
 'U.Group\n3.5',
 'Systems Evolution Inc.\n4.7',
 'Eventbrite\n4.4',
 'Centro\n4.1',
 'comScore\n2.5',
 'SullivanCotter\n4.2',
 'NPD\n3.9',
 'Bakery Agency\n4.3',
 'Blue Cross & Blue Shield of Rhode Island\n3.4',
 'Boys Town\n3.8',
 'The HSC Health Care System\n3.3',
 'Pro-Sphere Tek\n3.4',
 'Ameritas Life Insurance Corp\n3.0',
 'Genworth\n3.7',
 'Trace Data\n3.9',
 'Clearwater Analytics\n4.2',
 'Tekvalley, Corp.\n4.0',
 'BWX Technologies\n3.5',
 'Vermeer\n3.9',
 'L&T Infotech\n3.5',
 'OceanFirst Financial\n4.3',
 "Sotheby's\n3.6",
 'Vanda Pharmaceuticals\n2.3',
 'CK-12 Foundation\n4.1',
 'Opinion Dynamics\n4.2',
 'Applied Information Sciences\n4.6',
 'WK Dickson\n4.4',
 'Southwest Research Institute\n3.9',
 'Muso',
 'The Integer Group\n2.2',
 'Samba TV\n3.3',
 'SV Microwave\n3.4',
 'Sumo Logic\n3.8',
 'EAB\n3.5',
 'Brighthouse Financial\n3.5',
 'Citadel Federal Credit Union\n3.9',
 'CALIBRE Systems\n3.7',
 'Motorola Solutions\n3.7',
 'Reynolds American\n3.1',
 'Infosys\n3.0',
 'Alignment Healthcare\n3.5',
 'Cboe Global Markets\n3.7',
 'Guidepoint\n3.2',
 'Cerus Corporation\n2.1',
 'Vail Health\n3.7',
 'AstraZeneca\n3.9',
 'MathWorks\n4.4',
 'MetroStar Systems\n3.4',
 'Audentes Therapeutics\n2.9',
 'National Interstate\n3.3',
 'Moser Consulting\n4.5',
 'Mcphail Associates\n3.3',
 'Crown Bioscience\n2.4',
 'HOVER\n4.8',
 'Q2 Solutions\n2.9',
 'Arbella Insurance\n3.4',
 'Kronos Bio',
 'Associated Banc-Corp\n3.8',
 'Genesys\n4.3',
 'Moda Operandi\n1.9',
 'QK\n4.7',
 'Santander\n3.1',
 'Tivity Health\n3.4',
 'BRMi\n4.4',
 'Luminar Technologies\n3.9',
 'Emtec, Inc.\n3.9',
 'Veterans United Home Loans\n4.7',
 'Praetorian\n4.7',
 'Agios Pharmaceuticals\n3.8',
 'Glassdoor\n4.0',
 'Assurant\n3.4',
 'F&G\n3.7',
 'GreatAmerica Financial Services\n4.6',
 'Acceleron Pharma\n4.4',
 'AmeriHealth Caritas\n3.0',
 'Strategic Employment Partners\n4.7',
 'Catholic Health Initiatives\n3.2',
 'FLEETCOR\n2.7',
 'Applied Research Laboratories\n3.7',
 'Raytheon\n3.7',
 'RTI International\n4.3',
 'TRANZACT\n3.6',
 'United BioSource\n2.1',
 'Figure Eight\n3.9',
 'Royce Geospatial\n5.0',
 'Citi\n3.6',
 'Sage Intacct\n4.7',
 'Scale AI\n3.5',
 'Change Healthcare\n2.7',
 'MZ\n3.4',
 'HG Insights\n4.7',
 '1-800-FLOWERS.COM, Inc.\n2.8',
 'CBS Interactive\n3.5',
 'Samsung Research America\n3.7',
 'Lorven Technologies Inc\n4.0',
 'CareDx\n2.5',
 'Serigor Inc.\n3.9',
 'Leidos\n3.4',
 'Beckman Coulter Diagnostics\n3.6',
 'IHS Markit\n3.5',
 'ALIN',
 'e-IT Professionals Corp.\n3.5',
 'TechProjects\n4.8',
 'Biz2Credit Inc\n4.0',
 'PeoplesBank\n4.2',
 'Capgemini\n3.8',
 'GNY Insurance Companies\n3.7',
 'Conch Technologies, Inc\n4.6',
 'Medidata Solutions\n4.3',
 'Quartet Health\n3.9',
 'Success Academy Charter Schools\n3.1',
 'AXION Healthcare Solutions\n3.6',
 'ExecOnline\n4.2',
 'Mteq\n4.0',
 'Brillient\n3.7',
 'Entefy\n4.4',
 'Trace3\n3.4',
 'Saama Technologies Inc\n3.5',
 'Two Sigma\n4.4',
 'Strategic Financial Solutions\n4.0',
 'Remedy BPCI Partners, LLC.\n3.4',
 'The Climate Corporation\n3.2',
 'Crossix Solutions\n3.5',
 'GSK\n3.9',
 'Factual\n4.3',
 'TriNet\n3.3',
 'Signpost\n3.9',
 'Adobe\n4.0',
 'Equian LLC\n3.2',
 'Information Builders\n3.2',
 'Greenway Health\n3.0',
 'Confluent\n4.7',
 'Life360\n3.9',
 'IQVIA\n3.6',
 'Riverside Research Institute\n3.6',
 'Icon Health and Fitness\n3.1',
 'Shipt\n3.8',
 'Monte Rosa Therapeutics',
 'IntraEdge\n3.4',
 'COUNTRY Financial\n3.8',
 'Mentor Graphics\n4.1',
 'Maxar Technologies\n3.7',
 'ICW Group\n2.8',
 'Exelixis\n3.0',
 'Grand Rounds\n4.2',
 'SPINS, LLC\n3.5',
 'DTCC\n3.3',
 'Carilion Clinic\n3.7',
 'DoubleVerify\n3.2',
 'Mitsubishi Electric Research Labs\n4.6',
 'Rodan and Fields, LLC\n2.2',
 'DESC\n3.4',
 'Johns Hopkins Health Care\n3.3',
 'Community Behavioral Health\n3.7',
 'FORMA THERAPEUTICS\n3.8',
 'Bridg\n2.7',
 'Charter Spectrum\n3.5',
 'CompQsoft\n3.4',
 'Solugenix Corporation\n4.3',
 'West Coast University\n2.6',
 'SoftBank Robotics\n3.8',
 'SkySync\n5.0',
 'DatamanUSA, LLC\n3.4',
 '23andMe\n4.0',
 'Fivestars\n3.9']

In [32]:
# Clean Company_Name by removing extra information (like ratings)
df['Company_Name'] = df['Company_Name'].str.split('\n').str[0]

In [33]:
# Again check after removing extra info
list(df['Company_Name'].unique())

['Tecolote Research',
 'University of Maryland Medical System',
 'KnowBe4',
 'PNNL',
 'Affinity Solutions',
 'CyrusOne',
 'ClearOne Advantage',
 'Logic20/20',
 'Rochester Regional Health',
 '<intent>',
 'Wish',
 'ManTech',
 'Walmart',
 'Yesler',
 'Takeda Pharmaceuticals',
 'Audible',
 'Blueprint Medicines',
 'h2o.ai',
 'Nuna',
 'Pinnacol Assurance',
 'Porch',
 'Health IQ',
 'Truckstop.com',
 'SMC 3',
 'Novetta',
 'Pfizer',
 'First Tech Federal Credit Union',
 'The Hanover Insurance Group',
 'Amrock',
 'Novartis',
 'Juniper Networks',
 'New England Biolabs',
 'Clarity Insights',
 'Esri',
 'Systems & Technology Research',
 'Sartorius',
 'Lancer Insurance',
 'Sauce Labs',
 'Persivia',
 'Edgewell Personal Care',
 'Equity Residential',
 'BPA Services',
 'Visa Inc.',
 'Intrado',
 'Centauri',
 'Caterpillar',
 'Zimmerman Advertising',
 'Liberty Mutual Insurance',
 'Torch Technologies, Inc.',
 'Swiss Re',
 'Northrop Grumman',
 'Netskope',
 '1904labs',
 'The David J. Joseph Company',
 'USEReady',
 'Bill.com',
 'Pacific Northwest National Laboratory',
 "DICK'S Sporting Goods - Corporate",
 'Berg Health',
 'Oversight Systems',
 'C Space',
 'Numeric, LLC',
 'HP Inc.',
 'SpringML',
 'Grainger',
 'EAG Laboratories',
 'The Buffalo Group',
 'Carmeuse',
 'GNS Healthcare',
 'Peraton',
 'Pactera',
 'Nurx',
 'webfx.com',
 'Johns Hopkins University Applied Physics Laboratory',
 'Productive Edge',
 'Excella Consulting',
 'Gensco',
 'goTRG',
 'NMR Consulting',
 'iSeatz',
 'Nektar Therapeutics',
 'TransUnion',
 'IT Concepts',
 'Scientific Research Corporation',
 'General Dynamics Information Technology',
 'MITRE',
 'DentaQuest',
 'Redjack',
 '7Park Data',
 'Rapid Response Monitoring',
 'Trilogy Ed',
 'Gallup',
 'CapTech',
 'American Axle & Manufacturing',
 'CentralReach',
 'Integrate',
 'Boys Town Hospital',
 'Demandbase',
 'Sapphire Digital',
 'Formation',
 'Autodesk',
 "Beck's Hybrids",
 'DrFirst',
 'Object Partners',
 'L.A. Care Health Plan',
 'Red Ventures',
 'Quick Base',
 'The E.W. Scripps Company',
 'Upside Business Travel',
 'Synagro',
 'Alliance Source Testing',
 'Accuride International',
 'Full Potential Solutions',
 'Maven Wave Partners',
 'First Command Financial Services, Inc.',
 'Pharmavite',
 'BioMarin Pharmaceutical',
 'Stratagem Group',
 'PA Consulting',
 'Gridiron IT',
 'Evolve Vacation Rental',
 'The Church of Jesus Christ of Latter-day Saints',
 'Maximus Real Estate Partners',
 'Software Engineering Institute',
 'AVANADE',
 'PatientPoint',
 'BlueCross BlueShield of Tennessee',
 'KSM Consulting',
 'Cogo Labs',
 'Church & Dwight',
 'MassMutual',
 'Genentech',
 'Legal & General America',
 'Western Digital',
 'Sunovion',
 'National Student Clearinghouse',
 'Tower Health',
 'State of Wisconsin Investment Board',
 'Rubius Therapeutics',
 'OneMagnify',
 'IZEA',
 'Vionic Group',
 'Dodge Data & Analytics',
 'Plymouth Rock Assurance',
 'CA-One Tech Cloud',
 'Beebe Healthcare',
 'Argo Group US',
 'Associated Electric Cooperative',
 'PennyMac',
 'Zest AI',
 'DECISIVE ANALYTICS Corporation',
 'Karyopharm Therapeutics Inc.',
 'Tempus Labs',
 'Recursion Pharmaceuticals',
 'P2 Energy Solutions',
 'ClearEdge',
 'Tapjoy',
 'Credit Sesame',
 'San Manuel Casino',
 'Texas Health Huguley Hospital',
 'Teasdale Latin Foods',
 'Central California Alliance for Health',
 'Pilot Flying J Travel Centers LLC',
 "Palermo's Pizza",
 'Advanced BioScience Laboratories',
 'Echo Global Logistics',
 'Lockheed Martin',
 'Acuity Insurance',
 'Fareportal',
 'Veterans Affairs, Veterans Health Administration',
 'Credera',
 'Spectrum Communications and Consulting',
 'NCSOFT',
 'Dayton Freight Lines, Inc.',
 'Community Action Partnership of San Luis Obispo',
 'TrueAccord',
 'DRB Systems',
 'Corcentric',
 'U.Group',
 'Systems Evolution Inc.',
 'Eventbrite',
 'Centro',
 'comScore',
 'SullivanCotter',
 'NPD',
 'Bakery Agency',
 'Blue Cross & Blue Shield of Rhode Island',
 'Boys Town',
 'The HSC Health Care System',
 'Pro-Sphere Tek',
 'Ameritas Life Insurance Corp',
 'Genworth',
 'Trace Data',
 'Clearwater Analytics',
 'Tekvalley, Corp.',
 'BWX Technologies',
 'Vermeer',
 'L&T Infotech',
 'OceanFirst Financial',
 "Sotheby's",
 'Vanda Pharmaceuticals',
 'CK-12 Foundation',
 'Opinion Dynamics',
 'Applied Information Sciences',
 'WK Dickson',
 'Southwest Research Institute',
 'Muso',
 'The Integer Group',
 'Samba TV',
 'SV Microwave',
 'Sumo Logic',
 'EAB',
 'Brighthouse Financial',
 'Citadel Federal Credit Union',
 'CALIBRE Systems',
 'Motorola Solutions',
 'Reynolds American',
 'Infosys',
 'Alignment Healthcare',
 'Cboe Global Markets',
 'Guidepoint',
 'Cerus Corporation',
 'Vail Health',
 'AstraZeneca',
 'MathWorks',
 'MetroStar Systems',
 'Audentes Therapeutics',
 'National Interstate',
 'Moser Consulting',
 'Mcphail Associates',
 'Crown Bioscience',
 'HOVER',
 'Q2 Solutions',
 'Arbella Insurance',
 'Kronos Bio',
 'Associated Banc-Corp',
 'Genesys',
 'Moda Operandi',
 'QK',
 'Santander',
 'Tivity Health',
 'BRMi',
 'Luminar Technologies',
 'Emtec, Inc.',
 'Veterans United Home Loans',
 'Praetorian',
 'Agios Pharmaceuticals',
 'Glassdoor',
 'Assurant',
 'F&G',
 'GreatAmerica Financial Services',
 'Acceleron Pharma',
 'AmeriHealth Caritas',
 'Strategic Employment Partners',
 'Catholic Health Initiatives',
 'FLEETCOR',
 'Applied Research Laboratories',
 'Raytheon',
 'RTI International',
 'TRANZACT',
 'United BioSource',
 'Figure Eight',
 'Royce Geospatial',
 'Citi',
 'Sage Intacct',
 'Scale AI',
 'Change Healthcare',
 'MZ',
 'HG Insights',
 '1-800-FLOWERS.COM, Inc.',
 'CBS Interactive',
 'Samsung Research America',
 'Lorven Technologies Inc',
 'CareDx',
 'Serigor Inc.',
 'Leidos',
 'Beckman Coulter Diagnostics',
 'IHS Markit',
 'ALIN',
 'e-IT Professionals Corp.',
 'TechProjects',
 'Biz2Credit Inc',
 'PeoplesBank',
 'Capgemini',
 'GNY Insurance Companies',
 'Conch Technologies, Inc',
 'Medidata Solutions',
 'Quartet Health',
 'Success Academy Charter Schools',
 'AXION Healthcare Solutions',
 'ExecOnline',
 'Mteq',
 'Brillient',
 'Entefy',
 'Trace3',
 'Saama Technologies Inc',
 'Two Sigma',
 'Strategic Financial Solutions',
 'Remedy BPCI Partners, LLC.',
 'The Climate Corporation',
 'Crossix Solutions',
 'GSK',
 'Factual',
 'TriNet',
 'Signpost',
 'Adobe',
 'Equian LLC',
 'Information Builders',
 'Greenway Health',
 'Confluent',
 'Life360',
 'IQVIA',
 'Riverside Research Institute',
 'Icon Health and Fitness',
 'Shipt',
 'Monte Rosa Therapeutics',
 'IntraEdge',
 'COUNTRY Financial',
 'Mentor Graphics',
 'Maxar Technologies',
 'ICW Group',
 'Exelixis',
 'Grand Rounds',
 'SPINS, LLC',
 'DTCC',
 'Carilion Clinic',
 'DoubleVerify',
 'Mitsubishi Electric Research Labs',
 'Rodan and Fields, LLC',
 'DESC',
 'Johns Hopkins Health Care',
 'Community Behavioral Health',
 'FORMA THERAPEUTICS',
 'Bridg',
 'Charter Spectrum',
 'CompQsoft',
 'Solugenix Corporation',
 'West Coast University',
 'SoftBank Robotics',
 'SkySync',
 'DatamanUSA, LLC',
 '23andMe',
 'Fivestars']

In [34]:
# To see Location and Job_Location to compare both fields
df[['Location','Job_Location']].head(101)

                 Location Job_Location
0         Albuquerque, NM           NM
1           Linthicum, MD           MD
2          Clearwater, FL           FL
3            Richland, WA           WA
4            New York, NY           NY
5              Dallas, TX           TX
6           Baltimore, MD           MD
7            San Jose, CA           CA
8           Rochester, NY           NY
9            New York, NY           NY
10           San Jose, CA           CA
11          Chantilly, VA           VA
12              Plano, TX           TX
13            Seattle, WA           WA
14          Cambridge, MA           MA
15             Newark, NJ           NJ
16          Cambridge, MA           MA
17      Mountain View, CA           CA
18      San Francisco, CA           CA
19             Denver, CO           CO
20            Seattle, WA           WA
21             Dallas, TX           TX
22            Chicago, IL           IL
23         Louisville, KY           KY
24            Herndon, VA           VA
25          Cambridge, MA           MA
26          Hillsboro, OR           OR
27          Worcester, MA           MA
28             Groton, CT           CT
29         Clearwater, FL           FL
30           Richland, WA           WA
31            Detroit, MI           MI
32          Cambridge, MA           MA
33          Sunnyvale, CA           CA
34            Ipswich, MA           MA
35           San Jose, CA           CA
36           Redlands, CA           CA
37             Woburn, MA           MA
38            Fremont, CA           CA
39         Long Beach, NY           NY
40      San Francisco, CA           CA
41        Marlborough, MA           MA
42      San Francisco, CA           CA
43          Allendale, NJ           NJ
44            Chicago, IL           IL
45         Washington, DC           DC
46           Bellevue, WA           WA
47           Longmont, CO           CO
48        Beavercreek, OH           OH
49             Peoria, IL           IL
50    Fort Lauderdale, FL           FL
51             Boston, MA           MA
52         Huntsville, AL           AL
53             Armonk, NY           NY
54          San Diego, CA           CA
55        Albuquerque, NM           NM
56      San Francisco, CA           CA
57        Saint Louis, MO           MO
58          Baltimore, MD           MD
59             Dallas, TX           TX
60         Cincinnati, OH           OH
61           New York, NY           NY
62          Palo Alto, CA           CA
63           Richland, WA           WA
64         Coraopolis, PA           PA
65         Framingham, MA           MA
66            Atlanta, GA           GA
67             Boston, MA           MA
68       Philadelphia, PA           PA
69          Vancouver, WA           WA
70       Indianapolis, IN           IN
71        Lake Forest, IL           IL
72   Maryland Heights, MO           MO
73    Charlottesville, VA           VA
74         Pittsburgh, PA           PA
75          Vancouver, WA           WA
76      Mountain View, CA           CA
77          Cambridge, MA           MA
78          Chantilly, VA           VA
79           San Jose, CA           CA
80      San Francisco, CA           CA
81         Harrisburg, PA           PA
82             Laurel, MD           MD
83            Chicago, IL           IL
84          Arlington, VA           VA
85             Tacoma, WA           WA
86              Plano, TX           TX
87           San Jose, CA           CA
88              Miami, FL           FL
89         Huntsville, AL           AL
90        New Orleans, LA           LA
91      San Francisco, CA           CA
92            Atlanta, GA           GA
93           Landover, MD           MD
94     Patuxent River, MD           MD
95           Suitland, MD           MD
96             McLean, VA           VA
97       Fort Belvoir, VA           VA
98          Milwaukee, WI           WI
99      Silver Spring, MD           MD
100          New York, NY           NY

In [35]:
# Create new column 'State_Wise' and Extract state code from Location column
df['State_Wise'] = df['Location'].str.split(',').str[-1].str.strip()

In [36]:
# To see all unique company_employee_size in the dataset
list(df['Size'].unique())

['501 - 1000',
 '10000+',
 '1001 - 5000',
 '51 - 200',
 '201 - 500',
 '5001 - 10000',
 'Jan-50',
 'unknown']

In [37]:
# Create new column and Replace invalid size values ('Jan-50', 'unknown') with NaN
df['Company_Man_Power'] =df['Size'].replace(['Jan-50', 'unknown'], np.nan)

In [38]:
# Fill missing values (NaN) with 'Unknown' for better analyzing
df['Company_Man_Power'] = df['Company_Man_Power'].fillna('Unknown')

In [39]:
# After cleaning to see unique company_manpower_categories
list(df['Company_Man_Power'].unique())

['501 - 1000',
 '10000+',
 '1001 - 5000',
 '51 - 200',
 '201 - 500',
 '5001 - 10000',
 'Unknown']

In [40]:
# Define a function to categorize company size into meaningful groups with new column
def size_category(x):
    if x == '51 - 200':
        return 'Small'
    elif x in ['201 - 500', '501 - 1000']:
        return 'Medium'
    elif x in ['1001 - 5000', '5001 - 10000']:
        return 'Large'
    elif x == '10000+':
        return 'Very Large'
    else:
        return 'Unknown'

df['Company_Man_Power_Category'] = df['Company_Man_Power'].apply(size_category)

In [41]:
# Compare company man power and categorized size
df[['Company_Man_Power', 'Company_Man_Power_Category']].head(20)

   Company_Man_Power Company_Man_Power_Category
0         501 - 1000                     Medium
1             10000+                 Very Large
2         501 - 1000                     Medium
3        1001 - 5000                      Large
4           51 - 200                      Small
5          201 - 500                     Medium
6         501 - 1000                     Medium
7          201 - 500                     Medium
8             10000+                 Very Large
9           51 - 200                      Small
10        501 - 1000                     Medium
11      5001 - 10000                      Large
12            10000+                 Very Large
13         201 - 500                     Medium
14            10000+                 Very Large
15       1001 - 5000                      Large
16          51 - 200                      Small
17         201 - 500                     Medium
18          51 - 200                      Small
19        501 - 1000                     Medium

In [42]:
df.head(21)

,Job_Title,Salary_Estimate,Rating,Company_Name,Location,Headquarters,Size,Founded,Type_of_ownership,Industry,Sector,Revenue,Competitors,Hourly,Employer_provided,Lower_Salary,Upper_Salary,Avg_SalaryK,company_txt,Job_Location,Age,Python,spark,aws,excel,sql_,sas,keras,pytorch,scikit,tensor,hadoop,tableau,bi,flink,mongo,google_an,Job_Category,Seniority_Title,Degree_Required,Company_Rating,State_Wise,Company_Man_Power,Company_Man_Power_Category
0,data scientist,$53K-$91K (Glassdoor est.),3.8,Tecolote Research,"Albuquerque, NM","Goleta, CA",501 - 1000,1973,Company - Private,Aerospace & Defense,Aerospace & Defense,$50 to $100 million (USD),-1,0,0,53,91,72.0,Tecolote Research,NM,48,1,0,0,1,0,1,0,0,0,0,0,1,1,0,0,0,Data Scientist,Not Specified,Masters,3.8,NM,501 - 1000,Medium
1,healthcare data scientist,$63K-$112K (Glassdoor est.),3.4,University of Maryland Medical System,"Linthicum, MD","Baltimore, MD",10000+,1984,Other Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1,0,0,63,112,87.5,University of Maryland Medical System,MD,37,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Data Scientist,Not Specified,Masters,3.4,MD,10000+,Very Large
2,data scientist,$80K-$90K (Glassdoor est.),4.8,KnowBe4,"Clearwater, FL","Clearwater, FL",501 - 1000,2010,Company - Private,Security Services,Business Services,$100 to $500 million (USD),-1,0,0,80,90,85.0,KnowBe4,FL,11,1,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,Data Scientist,Not Specified,Masters,4.8,FL,501 - 1000,Medium
3,data scientist,$56K-$97K (Glassdoor est.),3.8,PNNL,"Richland, WA","Richland, WA",1001 - 5000,1965,Government,Energy,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa...",0,0,56,97,76.5,PNNL,WA,56,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Data Scientist,Not Specified,Not_Specified,3.8,WA,1001 - 5000,Large
4,data scientist,$86K-$143K (Glassdoor est.),2.9,Affinity Solutions,"New York, NY","New York, NY",51 - 200,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee",0,0,86,143,114.5,Affinity Solutions,NY,23,1,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,Data Scientist,Not Specified,Not_Specified,2.9,NY,51 - 200,Small
5,data scientist,$71K-$119K (Glassdoor est.),3.4,CyrusOne,"Dallas, TX","Dallas, TX",201 - 500,2000,Company - Public,Real Estate,Real Estate,$1 to $2 billion (USD),"Digital Realty, CoreSite, Equinix",0,0,71,119,95.0,CyrusOne,TX,21,1,0,1,1,1,0,0,0,0,0,0,0,1,0,1,0,Data Scientist,Not Specified,Not_Specified,3.4,TX,201 - 500,Medium
6,data scientist,$54K-$93K (Glassdoor est.),4.1,ClearOne Advantage,"Baltimore, MD","Baltimore, MD",501 - 1000,2008,Company - Private,Banks & Credit Unions,Finance,Unknown / Non-Applicable,-1,0,0,54,93,73.5,ClearOne Advantage,MD,13,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,Data Scientist,Not Specified,Not_Specified,4.1,MD,501 - 1000,Medium
7,data scientist,$86K-$142K (Glassdoor est.),3.8,Logic20/20,"San Jose, CA","Seattle, WA",201 - 500,2005,Company - Private,Consulting,Business Services,$25 to $50 million (USD),-1,0,0,86,142,114.0,Logic20/20,CA,16,1,1,1,1,1,0,0,1,0,1,0,0,0,0,0,0,Data Scientist,Not Specified,Masters,3.8,CA,201 - 500,Medium
8,research scientist,$38K-$84K (Glassdoor est.),3.3,Rochester Regional Health,"Rochester, NY","Rochester, NY",10000+,2014,Hospital,Health Care Services & Hospitals,Health Care,$500 million to $1 billion (USD),-1,0,0,38,84,61.0,Rochester Regional Health,NY,7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Other Scientist,Not Specified,PhD,3.3,NY,10000+,Very Large
9,data scientist,$120K-$160K (Glassdoor est.),4.6,<intent>,"New York, NY","New York, NY",51 - 200,2009,Company - Private,Internet,Information Technology,$100 to $500 million (USD),"Clicktripz, SmarterTravel",0,0,120,160,140.0,<intent>,NY,12,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Data Scientist,Not Specified,Not_Specified,4.6,NY,51 - 200,Small
10,data scientist,$126K-$201K (Glassdoor est.),3.5,Wish,"San Jose, CA","San Francisco, CA",501 - 1000,2011,Company - Private,Other Retail Stores,Retail,$1 to $2 billion (USD),-1,0,0,126,201,163.5,Wish,CA,10,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Data Scientist,Not Specified,Not_Specified,3.5,CA,501 - 1000,Medium
11,data scientist,$64K-$106K (Glassdoor est.),4.1,ManTech,"Chantilly, VA","Herndon, VA",5001 - 10000,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1,0,0,64,106,85.0,ManTech,VA,53,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,Data Scientist,Not Specified,Not_Specified,4.1,VA,5001 - 10000,Large
12,staff data scientist technology,$106K-$172K (Glassdoor est.),3.2,Walmart,"Plano, TX","Bentonville, AR",10000+,1962,Company - Public,"Department, Clothing, & Shoe Stores",Retail,$10+ billion (USD),"Target, Costco Wholesale, Amazon",0,0,106,172,139.0,Walmart,TX,59,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,Data Scientist,Not Specified,Masters,3.2,TX,10000+,Very Large
13,data analyst,$46K-$85K (Glassdoor est.),4.1,Yesler,"Seattle, WA","Seattle, WA",201 - 500,2012,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,-1,0,0,46,85,65.5,Yesler,WA,9,1,1,1,1,1,0,0,0,0,0,0,1,1,0,0,0,Data Analyst,Not Specified,Not_Specified,4.1,WA,201 - 500,Medium
14,data scientist,$83K-$144K (Glassdoor est.),3.7,Takeda Pharmaceuticals,"Cambridge, MA","OSAKA, Japan",10000+,1781,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),"Novartis, Baxter, Pfizer",0,0,83,144,113.5,Takeda Pharmaceuticals,MA,240,1,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,Data Scientist,Not Specified,Masters,3.7,MA,10000+,Very Large
15,data engineer i,$102K-$190K (Glassdoor est.),3.6,Audible,"Newark, NJ","Newark, NJ",1001 - 5000,1995,Subsidiary or Business Segment,Motion Picture Production & Distribution,Media,Unknown / Non-Applicable,-1,0,0,102,190,146.0,Audible,NJ,26,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,Data Engineer,Not Specified,Not_Specified,3.6,NJ,1001 - 5000,Large
16,scientist i ii biology,$67K-$137K (Glassdoor est.),3.9,Blueprint Medicines,"Cambridge, MA","Cambridge, MA",51 - 200,2011,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$1 to $5 million (USD),"bluebird bio, Agios Pharmaceuticals, Celgene",0,0,67,137,102.0,Blueprint Medicines,MA,10,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,Other Scientist,Not Specified,PhD,3.9,MA,51 - 200,Small
17,customer data scientist,$118K-$189K (Glassdoor est.),4.3,h2o.ai,"Mountain View, CA","Mountain View, CA",201 - 500,2011,Company - Private,Enterprise Software & Network Solutions,Information Technology,Unknown / Non-Applicable,-1,0,0,118,189,153.5,h2o.ai,CA,10,1,1,1,1,0,0,0,0,0,0,1,0,0,0,0,0,Data Scientist,Not Specified,Masters,4.3,CA,201 - 500,Medium
18,data scientist health data analytics,$110K-$175K (Glassdoor est.),4.2,Nuna,"San Francisco, CA","San Francisco, CA",51 - 200,2010,Company - Private,Enterprise Software & Network Solutions,Information Technology,Unknown / Non-Applicable,-1,0,0,110,175,142.5,Nuna,CA,11,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,Data Scientist,Not Specified,Not_Specified,4.2,CA,51 - 200,Small
19,data scientist,$64K-$111K (Glassdoor est.),4.0,Pinnacol Assurance,"Denver, CO","Denver, CO",501 - 1000,1915,Nonprofit Organization,Insurance Carriers,Insurance,$500 million to $1 billion (USD),-1,0,0,64,111,87.5,Pinnacol Assurance,CO,106,1,0,0,1,1,0,1,1,1,1,0,0,0,0,0,0,Data Scientist,Not Specified,Masters,4.0,CO,501 - 1000,Medium
20,data scientist,$81K-$130K (Glassdoor est.),3.2,Porch,"Seattle, WA","Seattle, WA",201 - 500,2012,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,"Angie's List, HomeAdvisor, Thumbtack",0,0,81,130,105.5,Porch,WA,9,1,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,Data Scientist,Not Specified,Masters,3.2,WA,201 - 500,Medium

In [43]:
# After creating new column company_rating and company_size then drop the old column
df.drop(['Rating','Size'], axis=1, inplace=True)

In [44]:
# Convert Founded column to numeric and Replace invalid founded year (-1) with NaN
pd.to_numeric(df['Founded'], errors='coerce')
df['Founded_Year'] = df['Founded'].replace(-1, np.nan)

In [45]:
# To see unique founded_years after cleaning
list(df['Founded_Year'].unique())

[np.float64(1973.0),
 np.float64(1984.0),
 np.float64(2010.0),
 np.float64(1965.0),
 np.float64(1998.0),
 np.float64(2000.0),
 np.float64(2008.0),
 np.float64(2005.0),
 np.float64(2014.0),
 np.float64(2009.0),
 np.float64(2011.0),
 np.float64(1968.0),
 np.float64(1962.0),
 np.float64(2012.0),
 np.float64(1781.0),
 np.float64(1995.0),
 np.float64(1915.0),
 np.float64(2013.0),
 np.float64(1935.0),
 np.float64(1849.0),
 np.float64(1952.0),
 np.float64(1852.0),
 np.float64(1997.0),
 np.float64(1996.0),
 np.float64(1974.0),
 np.float64(1969.0),
 np.float64(1870.0),
 np.float64(1985.0),
 np.float64(nan),
 np.float64(2015.0),
 np.float64(1993.0),
 np.float64(1958.0),
 np.float64(1986.0),
 np.float64(1999.0),
 np.float64(1925.0),
 np.float64(1912.0),
 np.float64(2002.0),
 np.float64(1863.0),
 np.float64(1939.0),
 np.float64(2016.0),
 np.float64(1885.0),
 np.float64(2006.0),
 np.float64(1948.0),
 np.float64(2003.0),
 np.float64(1927.0),
 np.float64(1978.0),
 np.float64(1860.0),
 np.float64(2017.0),
 np.float64(1942.0),
 np.float64(1990.0),
 np.float64(1988.0),
 np.float64(2001.0),
 np.float64(2007.0),
 np.float64(1992.0),
 np.float64(1994.0),
 np.float64(1977.0),
 np.float64(2019.0),
 np.float64(1982.0),
 np.float64(1937.0),
 np.float64(1878.0),
 np.float64(1966.0),
 np.float64(1971.0),
 np.float64(1943.0),
 np.float64(1987.0),
 np.float64(1945.0),
 np.float64(1846.0),
 np.float64(1851.0),
 np.float64(1976.0),
 np.float64(1981.0),
 np.float64(1970.0),
 np.float64(1951.0),
 np.float64(1967.0),
 np.float64(1961.0),
 np.float64(1964.0),
 np.float64(1930.0),
 np.float64(1917.0),
 np.float64(1883.0),
 np.float64(1887.0),
 np.float64(2004.0),
 np.float64(1850.0),
 np.float64(1902.0),
 np.float64(1744.0),
 np.float64(1929.0),
 np.float64(1947.0),
 np.float64(1991.0),
 np.float64(1989.0),
 np.float64(1928.0),
 np.float64(1875.0),
 np.float64(1913.0),
 np.float64(1972.0),
 np.float64(1856.0),
 np.float64(1983.0),
 np.float64(1922.0),
 np.float64(1812.0),
 np.float64(1914.0),
 np.float64(1980.0),
 np.float64(1954.0),
 np.float64(1830.0),
 np.float64(1975.0),
 np.float64(1899.0),
 np.float64(1979.0),
 np.float64(1889.0)]

In [46]:
# Fill missing founded_years values with 'Unknown'
df['Founded_Year'].fillna('Unknown')

0       1973.0
1       1984.0
2       2010.0
3       1965.0
4       1998.0
5       2000.0
6       2008.0
7       2005.0
8       2014.0
9       2009.0
10      2011.0
11      1968.0
12      1962.0
13      2012.0
14      1781.0
15      1995.0
16      2011.0
17      2011.0
18      2010.0
19      1915.0
20      2012.0
21      2013.0
22      1995.0
23      1935.0
24      2012.0
25      1849.0
26      1952.0
27      1852.0
28      1849.0
29      2010.0
30      1965.0
31      1997.0
32      1996.0
33      1996.0
34      1974.0
35      2008.0
36      1969.0
37      2010.0
38      1870.0
39      1985.0
40      2008.0
41     Unknown
42      2010.0
43      2015.0
44      1993.0
45     Unknown
46      1958.0
47      1986.0
48      1999.0
49      1925.0
50      1984.0
51      1912.0
52      2002.0
53      1863.0
54      1939.0
55      1870.0
56      2012.0
57      2016.0
58      2008.0
59      2000.0
60      1885.0
61      2011.0
62      2006.0
63      1965.0
64      1948.0
65      2006.0
66      2003.0
67      1999.0
68     Unknown
69      1939.0
70      2015.0
71      1927.0
72      1978.0
73      2010.0
74      1860.0
75      1939.0
76      2011.0
77      2000.0
78      2017.0
79      1995.0
80      2016.0
81      1997.0
82      1942.0
83      2008.0
84      2002.0
85      1948.0
86      1962.0
87      2005.0
88      2008.0
89      1996.0
90      1999.0
91      1990.0
92      1968.0
93      2003.0
94      1988.0
95      1996.0
96      1958.0
97      2010.0
98      2001.0
99      2007.0
100     2012.0
101     1992.0
102     2015.0
103     1935.0
104     1997.0
105     1994.0
106     2012.0
107     2010.0
108     1977.0
109     2006.0
110     2019.0
111     1781.0
112     2009.0
113     2015.0
114     1982.0
115     1937.0
116     2000.0
117     1996.0
118     1997.0
119     2000.0
120     1999.0
121     1878.0
122     2015.0
123     1993.0
124     1986.0
125     2000.0
126     1966.0
127     2017.0
128     1958.0
129     2008.0
130     2012.0
131     1958.0
132     1971.0
133     1997.0
134     2007.0
135     1943.0
136     1968.0
137     2011.0
138     2017.0
139     2008.0
140     2011.0
141    Unknown
142     2013.0
143     1984.0
144     1965.0
145     2000.0
146     2011.0
147     1987.0
148     1945.0
149     1965.0
150     2010.0
151     2008.0
152     2005.0
153     1846.0
154     1851.0
155     1976.0
156     1996.0
157     1781.0
158     1981.0
159     1970.0
160     2013.0
161     2010.0
162    Unknown
163     2010.0
164     1993.0
165     2017.0
166     1951.0
167     2013.0
168     1982.0
169     1967.0
170     2006.0
171     2006.0
172     1781.0
173     2014.0
174     1781.0
175     1982.0
176     2017.0
177     1935.0
178     1781.0
179     1948.0
180     1961.0
181     1984.0
182     2008.0
183     2009.0
184     1996.0
185     1852.0
186    Unknown
187     2015.0
188     2013.0
189    Unknown
190     2014.0
191     2002.0
192     2013.0
193     2007.0
194     2014.0
195     2010.0
196     1986.0
197     1977.0
198    Unknown
199     1984.0
200     1996.0
201     1958.0
202     1935.0
203     1964.0
204     1961.0
205     2005.0
206     1995.0
207     1995.0
208     1925.0
209     2002.0
210     1930.0
211     1999.0
212     2010.0
213     1846.0
214     2005.0
215     1992.0
216     1997.0
217     1958.0
218     1981.0
219     1851.0
220     1976.0
221     1996.0
222    Unknown
223     1781.0
224     2013.0
225     1984.0
226     1970.0
227     1981.0
228     1996.0
229     2019.0
230    Unknown
231     1849.0
232     1935.0
233     1992.0
234     2010.0
235     2006.0
236     2001.0
237     1993.0
238     1999.0
239     1992.0
240     1966.0
241     2010.0
242     1951.0
243     1976.0
244     1939.0
245     1917.0
246     2017.0
247     1883.0
248     2006.0
249     1887.0
250     1982.0
251     2004.0
252     2013.0
253     1967.0
254     1849.0
255     2012.0
256    Unknown
257     2006.0
258     2000.0
259     1781.0
260     2006.0
261     1781.0
262     2014.0
263     2004.0
264    Unknown
265     1850.0
266     2017.0
267     2008.0
268     1982.0
269     1948.0
270     1781.0
271     1935.0
272     1948.0
273     1997.0
274     1902.0
275     1961.0
276     1984.0
277     1744.0
278     1952.0
279     1997.0
280     2003.0
281     2009.0
282     2012.0
283     2007.0
284     2008.0
285     1996.0
286     1987.0
287     1982.0
288     1863.0
289     1781.0
290     1929.0
291     1852.0
292     1976.0
293     1851.0
294     2015.0
295     1996.0
296     1968.0
297     1996.0
298     1982.0
299     1947.0
300    Unknown
301     2015.0
302     1996.0
303     1996.0
304     1993.0
305    Unknown
306     1968.0
307    Unknown
308     1965.0
309     1851.0
310     2013.0
311     1969.0
312     2014.0
313     2013.0
314     2008.0
315     1991.0
316     2002.0
317     2015.0
318     2010.0
319     2007.0
320     2017.0
321     1998.0
322     1937.0
323     2014.0
324     1989.0
325     1851.0
326     1969.0
327     1974.0
328     2007.0
329     1928.0
330     2010.0
331     1875.0
332     1851.0
333     1981.0
334     2013.0
335     1986.0
336     2010.0
337     1977.0
338     1973.0
339    Unknown
340     2003.0
341    Unknown
342     1781.0
343     1984.0
344     2008.0
345     1966.0
346     1996.0
347     1958.0
348     2010.0
349     1913.0
350     1915.0
351     1964.0
352     1984.0
353     1999.0
354     1912.0
355     2012.0
356     1961.0
357     1935.0
358     1875.0
359     1989.0
360     1996.0
361     1968.0
362     1958.0
363     1976.0
364     1875.0
365     2006.0
366     2011.0
367     2015.0
368     2015.0
369     1988.0
370    Unknown
371     1984.0
372     1984.0
373    Unknown
374     1851.0
375     1849.0
376     1870.0
377     2009.0
378     2002.0
379     1990.0
380     2010.0
381     1912.0
382     1972.0
383     1856.0
384     1981.0
385     2004.0
386     2012.0
387     1995.0
388     2002.0
389     2010.0
390     1943.0
391     2008.0
392     1961.0
393     1875.0
394     2005.0
395     2007.0
396     1969.0
397     1978.0
398     1925.0
399     1993.0
400    Unknown
401     1965.0
402     1992.0
403     2003.0
404    Unknown
405     1983.0
406     2006.0
407     1965.0
408     1996.0
409     2000.0
410     1912.0
411     1947.0
412    Unknown
413     1875.0
414     1922.0
415     1958.0
416     1989.0
417     2003.0
418     2008.0
419     2007.0
420     2002.0
421     1875.0
422     1870.0
423     2016.0
424     2014.0
425     1851.0
426     1965.0
427     2013.0
428     1812.0
429     1999.0
430     2016.0
431     1969.0
432     2014.0
433     2007.0
434     2008.0
435     2010.0
436     1976.0
437     1992.0
438    Unknown
439     2013.0
440     2008.0
441     2002.0
442     1991.0
443     2010.0
444     2007.0
445     2015.0
446     1988.0
447     2010.0
448     2012.0
449    Unknown
450     2017.0
451    Unknown
452    Unknown
453     1969.0
454     1935.0
455     2016.0
456    Unknown
457     1998.0
458    Unknown
459     2011.0
460     2007.0
461     1885.0
462     1967.0
463     1914.0
464     1937.0
465    Unknown
466     1999.0
467     2014.0
468     1989.0
469     1939.0
470     1851.0
471     2007.0
472     1939.0
473     1958.0
474     2014.0
475     1928.0
476     2010.0
477     2006.0
478     1875.0
479     1981.0
480     1851.0
481     1980.0
482     2013.0
483     2012.0
484     1954.0
485     1913.0
486     2006.0
487     2012.0
488     2010.0
489     1973.0
490     1986.0
491     2002.0
492     1977.0
493    Unknown
494     1939.0
495     1997.0
496     2001.0
497     1912.0
498     1913.0
499     1958.0
500     2003.0
501    Unknown
502     2007.0
503     1781.0
504     1984.0
505     2011.0
506     2008.0
507     2006.0
508     2005.0
509     1966.0
510     2008.0
511    Unknown
512     1997.0
513     1830.0
514     2008.0
515     1988.0
516     2010.0
517     1996.0
518     1982.0
519     1913.0
520     1958.0
521     1863.0
522     1870.0
523     1915.0
524     1964.0
525     2004.0
526     1999.0
527     1984.0
528     1912.0
529     1975.0
530     1996.0
531     2012.0
532     1961.0
533     1935.0
534     1875.0
535     1989.0
536     1852.0
537     1996.0
538     1977.0
539     2002.0
540     1968.0
541     1958.0
542     1976.0
543     1875.0
544     2006.0
545     2015.0
546     2011.0
547     2015.0
548     2003.0
549     2014.0
550     1988.0
551    Unknown
552     2008.0
553     2017.0
554     1851.0
555     1830.0
556     2006.0
557     1984.0
558     1967.0
559    Unknown
560    Unknown
561     1851.0
562     1977.0
563     2014.0
564     1870.0
565     1849.0
566     2002.0
567     2012.0
568     2010.0
569     2012.0
570     1990.0
571     1851.0
572     1912.0
573     1996.0
574     2011.0
575    Unknown
576     1972.0
577     1981.0
578     1996.0
579     2006.0
580     1856.0
581    Unknown
582     2012.0
583     2004.0
584     2002.0
585     2009.0
586     2002.0
587     2017.0
588     1995.0
589     1943.0
590     2010.0
591     1961.0
592     1925.0
593     2005.0
594     2008.0
595     2007.0
596     1875.0
597     1981.0
598    Unknown
599     1972.0
600     2007.0
601     1969.0
602     1978.0
603    Unknown
604     1994.0
605     1965.0
606     1992.0
607     2003.0
608     1849.0
609    Unknown
610     1983.0
611     1994.0
612     2006.0
613     2011.0
614     1965.0
615     1995.0
616     1912.0
617     1996.0
618     2000.0
619     1973.0
620    Unknown
621     1947.0
622     1875.0
623     1922.0
624     1958.0
625     1948.0
626     1913.0
627     1989.0
628     1899.0
629     2003.0
630     2008.0
631     2007.0
632     2008.0
633     1991.0
634     2002.0
635     2002.0
636     1875.0
637     1991.0
638     1984.0
639     1979.0
640     1889.0
641    Unknown
642     1994.0
643     1970.0
644     1961.0
645     2008.0
646     1922.0
647     2008.0
648     1912.0
649     2011.0
650     2006.0
651     1965.0
652     1981.0
653     1913.0
654     1980.0
655     2013.0
656     1989.0
657     2012.0
658    Unknown
659     1954.0
660     2006.0
661     2012.0
662     2010.0
663     1986.0
664     1973.0
665     2002.0
666     1977.0
667     1939.0
668    Unknown
669     1997.0
670     1913.0
671     1958.0
672     1885.0
673     2010.0
674     1997.0
675    Unknown
676     1781.0
677     2011.0
678     2007.0
679     2008.0
680     1984.0
681     2006.0
682     1966.0
683    Unknown
684     2005.0
685     1969.0
686     1997.0
687     2008.0
688     1997.0
689     2005.0
690     1830.0
691     2008.0
692     1958.0
693     2011.0
694     1988.0
695     1999.0
696     1996.0
697     2010.0
698     1982.0
699     1913.0
700    Unknown
701     1958.0
702     1913.0
703     1915.0
704     1964.0
705     2004.0
706     1999.0
707     1984.0
708     1912.0
709     1975.0
710     1996.0
711     1935.0
712     2012.0
713     1961.0
714    Unknown
715     1875.0
716     2006.0
717     1989.0
718     1996.0
719     1977.0
720     1852.0
721     2002.0
722     1968.0
723     1958.0
724     1976.0
725     1875.0
726     2006.0
727     2011.0
728     2015.0
729     2015.0
730    Unknown
731     1988.0
732     2007.0
733     2008.0
734     1851.0
735     2011.0
736     2017.0
737     1830.0
738     2006.0
739     1984.0
740    Unknown
741     1967.0
Name: Founded_Year, dtype: object

In [47]:
# Calculate company_age (current year - founded year)
df['Company_Age'] = 2026 - df['Founded_Year']

In [48]:
# To verify Founded_Year and Company_Age
df[['Founded_Year','Company_Age']].head(50)

    Founded_Year  Company_Age
0         1973.0         53.0
1         1984.0         42.0
2         2010.0         16.0
3         1965.0         61.0
4         1998.0         28.0
5         2000.0         26.0
6         2008.0         18.0
7         2005.0         21.0
8         2014.0         12.0
9         2009.0         17.0
10        2011.0         15.0
11        1968.0         58.0
12        1962.0         64.0
13        2012.0         14.0
14        1781.0        245.0
15        1995.0         31.0
16        2011.0         15.0
17        2011.0         15.0
18        2010.0         16.0
19        1915.0        111.0
20        2012.0         14.0
21        2013.0         13.0
22        1995.0         31.0
23        1935.0         91.0
24        2012.0         14.0
25        1849.0        177.0
26        1952.0         74.0
27        1852.0        174.0
28        1849.0        177.0
29        2010.0         16.0
30        1965.0         61.0
31        1997.0         29.0
32        1996.0         30.0
33        1996.0         30.0
34        1974.0         52.0
35        2008.0         18.0
36        1969.0         57.0
37        2010.0         16.0
38        1870.0        156.0
39        1985.0         41.0
40        2008.0         18.0
41           NaN          NaN
42        2010.0         16.0
43        2015.0         11.0
44        1993.0         33.0
45           NaN          NaN
46        1958.0         68.0
47        1986.0         40.0
48        1999.0         27.0
49        1925.0        101.0

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 742 entries, 0 to 741
Data columns (total 44 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Job_Title                   742 non-null    object
 1   Salary_Estimate             742 non-null    object
 2   Company_Name                742 non-null    object
 3   Location                    742 non-null    object
 4   Headquarters                742 non-null    object
 5   Founded                     742 non-null    int64
 6   Type_of_ownership           742 non-null    object
 7   Industry                    742 non-null    object
 8   Sector                      742 non-null    object
 9   Revenue                     742 non-null    object
 10  Competitors                 742 non-null    object
 11  Hourly                      742 non-null    int64
 12  Employer_provided           742 non-null    int64
 13  Lower_Salary                742 non-null    int64
 14  Upper_Salary                742 non-null    int64
 15  Avg_SalaryK                 742 non-null    float64
 16  company_txt                 742 non-null    object
 17  Job_Location                742 non-null    object
 18  Age                         742 non-null    int64
 19  Python                      742 non-null    int64
 20  spark                       742 non-null    int64
 21  aws                         742 non-null    int64
 22  excel                       742 non-null    int64
 23  sql_                        742 non-null    int64
 24  sas                         742 non-null    int64
 25  keras                       742 non-null    int64
 26  pytorch                     742 non-null    int64
 27  scikit                      742 non-null    int64
 28  tensor                      742 non-null    int64
 29  hadoop                      742 non-null    int64
 30  tableau                     742 non-null    int64
 31  bi                          742 non-null    int64
 32  flink                       742 non-null    int64
 33  mongo                       742 non-null    int64
 34  google_an                   742 non-null    int64
 35  Job_Category                742 non-null    object
 36  Seniority_Title             742 non-null    object
 37  Degree_Required             742 non-null    object
 38  Company_Rating              742 non-null    float64
 39  State_Wise                  742 non-null    object
 40  Company_Man_Power           742 non-null    object
 41  Company_Man_Power_Category  742 non-null    object
 42  Founded_Year                692 non-null    float64
 43  Company_Age                 692 non-null    float64
dtypes: float64(4), int64(22), object(18)
memory usage: 255.2+ KB

In [50]:
# Convert Founded_Year to nullable integer type for clean format and to keep missing values
df['Founded_Year'] = df['Founded_Year'].astype('Int64')

In [51]:
# Convert Company_Age to nullable integer type for better analysis
df['Company_Age'] = df['Company_Age'].astype('Int64')

In [52]:
# After creating new column Founded_Year and company_age then drop the old column
df.drop(['Founded','Age'], axis=1, inplace=True)

In [53]:
# To see unique ownership_types to understand data variations
list(df['Type_of_ownership'].unique())

['Company - Private',
 'Other Organization',
 'Government',
 'Company - Public',
 'Hospital',
 'Subsidiary or Business Segment',
 'Nonprofit Organization',
 'College / University',
 'School / School District']

In [54]:
# To standardize ownership types into clear categories and Apply mapping to create a new cleaned ownership_type column
ownership_map = {
    'Company - Private': 'Private',
    'Company - Public': 'Public',
    'Government': 'Government',
    'Nonprofit Organization': 'Nonprofit',
    'Hospital': 'Healthcare',
    'College / University': 'Education',
    'School / School District': 'Education',
    'Subsidiary or Business Segment': 'Subsidiary',
    'Other Organization': 'Other'
}

df['Ownership_Type'] = df['Type_of_ownership'].map(ownership_map)

In [55]:
# Check unique values after cleaning
list(df['Ownership_Type'].unique())

['Private',
 'Other',
 'Government',
 'Public',
 'Healthcare',
 'Subsidiary',
 'Nonprofit',
 'Education']

In [56]:
# Check unique values
list(df['Industry'].unique())

['Aerospace & Defense',
 'Health Care Services & Hospitals',
 'Security Services',
 'Energy',
 'Advertising & Marketing',
 'Real Estate',
 'Banks & Credit Unions',
 'Consulting',
 'Internet',
 'Other Retail Stores',
 'Research & Development',
 'Department, Clothing, & Shoe Stores',
 'Biotech & Pharmaceuticals',
 'Motion Picture Production & Distribution',
 'Enterprise Software & Network Solutions',
 'Insurance Carriers',
 'Insurance Agencies & Brokerages',
 'Logistics & Supply Chain',
 'Telecommunications Services',
 'IT Services',
 'Computer Hardware & Software',
 '-1',
 'Consumer Products Manufacturing',
 'Industrial Manufacturing',
 'Metals Brokers',
 'Financial Transaction Processing',
 'Sporting Goods Stores',
 'Staffing & Outsourcing',
 'Wholesale',
 'Mining',
 'Financial Analytics & Research',
 'Federal Agencies',
 'Education Training Services',
 'Transportation Equipment Manufacturing',
 'Farm Support Services',
 'TV Broadcast & Cable Networks',
 'Architectural & Engineering Services',
 'Brokerage Services',
 'Travel Agencies',
 'Religious Organizations',
 'Colleges & Universities',
 'Investment Banking & Asset Management',
 'Lending',
 'Gambling',
 'Food & Beverage Manufacturing',
 'Gas Stations',
 'Transportation Management',
 'Video Games',
 'Trucking',
 'Social Assistance',
 'Auctions & Galleries',
 'K-12 Education',
 'Telecommunications Manufacturing',
 'Stock Exchanges',
 'Construction',
 'Accounting',
 'Health Care Products Manufacturing',
 'Health, Beauty, & Fitness',
 'Consumer Product Rental',
 'Beauty & Personal Accessories Stores']

In [57]:
# Clean Industry column convert to string, remove spaces, and replace invalid '-1' with 'Unknown'
df['Industry'] = df['Industry'].astype(str).str.strip().replace('-1', 'Unknown')

In [58]:
# Check unique values after cleaning
list(df['Industry'].unique())

['Aerospace & Defense',
 'Health Care Services & Hospitals',
 'Security Services',
 'Energy',
 'Advertising & Marketing',
 'Real Estate',
 'Banks & Credit Unions',
 'Consulting',
 'Internet',
 'Other Retail Stores',
 'Research & Development',
 'Department, Clothing, & Shoe Stores',
 'Biotech & Pharmaceuticals',
 'Motion Picture Production & Distribution',
 'Enterprise Software & Network Solutions',
 'Insurance Carriers',
 'Insurance Agencies & Brokerages',
 'Logistics & Supply Chain',
 'Telecommunications Services',
 'IT Services',
 'Computer Hardware & Software',
 'Unknown',
 'Consumer Products Manufacturing',
 'Industrial Manufacturing',
 'Metals Brokers',
 'Financial Transaction Processing',
 'Sporting Goods Stores',
 'Staffing & Outsourcing',
 'Wholesale',
 'Mining',
 'Financial Analytics & Research',
 'Federal Agencies',
 'Education Training Services',
 'Transportation Equipment Manufacturing',
 'Farm Support Services',
 'TV Broadcast & Cable Networks',
 'Architectural & Engineering Services',
 'Brokerage Services',
 'Travel Agencies',
 'Religious Organizations',
 'Colleges & Universities',
 'Investment Banking & Asset Management',
 'Lending',
 'Gambling',
 'Food & Beverage Manufacturing',
 'Gas Stations',
 'Transportation Management',
 'Video Games',
 'Trucking',
 'Social Assistance',
 'Auctions & Galleries',
 'K-12 Education',
 'Telecommunications Manufacturing',
 'Stock Exchanges',
 'Construction',
 'Accounting',
 'Health Care Products Manufacturing',
 'Health, Beauty, & Fitness',
 'Consumer Product Rental',
 'Beauty & Personal Accessories Stores']

In [59]:
# Check unique values
list(df['Sector'].unique())

['Aerospace & Defense',
 'Health Care',
 'Business Services',
 'Oil, Gas, Energy & Utilities',
 'Real Estate',
 'Finance',
 'Information Technology',
 'Retail',
 'Biotech & Pharmaceuticals',
 'Media',
 'Insurance',
 'Transportation & Logistics',
 'Telecommunications',
 '-1',
 'Manufacturing',
 'Mining & Metals',
 'Government',
 'Education',
 'Agriculture & Forestry',
 'Travel & Tourism',
 'Non-Profit',
 'Arts, Entertainment & Recreation',
 'Construction, Repair & Maintenance',
 'Accounting & Legal',
 'Consumer Services']

In [60]:
# Clean Sector column convert to string, remove spaces, and replace invalid '-1' with 'Unknown'
df['Sector'] = df['Sector'].astype(str).str.strip().replace('-1', 'Unknown')

In [61]:
# Check unique values after cleaning
list(df['Sector'].unique())

['Aerospace & Defense',
 'Health Care',
 'Business Services',
 'Oil, Gas, Energy & Utilities',
 'Real Estate',
 'Finance',
 'Information Technology',
 'Retail',
 'Biotech & Pharmaceuticals',
 'Media',
 'Insurance',
 'Transportation & Logistics',
 'Telecommunications',
 'Unknown',
 'Manufacturing',
 'Mining & Metals',
 'Government',
 'Education',
 'Agriculture & Forestry',
 'Travel & Tourism',
 'Non-Profit',
 'Arts, Entertainment & Recreation',
 'Construction, Repair & Maintenance',
 'Accounting & Legal',
 'Consumer Services']

In [62]:
# Check total missing (null) values in salary-related columns
df[['Lower_Salary','Upper_Salary','Avg_SalaryK']].isnull().sum()

Lower_Salary    0
Upper_Salary    0
Avg_SalaryK     0
dtype: int64

In [63]:
# To see few rows of selected skill columns to inspect data
df[['Python','excel','sql_']].head()

   Python  excel  sql_
0       1      1     0
1       1      0     0
2       1      1     1
3       1      0     0
4       1      1     1

In [64]:
# List of all skill-related columns for processing and Convert all skill columns to numeric
skill_cols = ['Python','spark','aws','excel','sql_','sas','keras','pytorch',
              'scikit','tensor','hadoop','tableau','bi',
              'flink','mongo','google_an']

df[skill_cols] = df[skill_cols].apply(pd.to_numeric, errors='coerce')

In [65]:
# Replace missing values (NaN) with 0
df[skill_cols] = df[skill_cols].fillna(0)

In [66]:
# To check calculate total demand for each skill and sort them from highest to lowest
df[skill_cols].sum().sort_values(ascending=False)

Python       392
excel        388
sql_         380
aws          176
spark        167
tableau      148
hadoop       124
tensor        72
sas           66
bi            56
scikit        54
pytorch       39
mongo         37
keras         29
google_an     14
flink         10
dtype: int64

In [67]:
# Rename columns to more standardized names for better understanding
df.rename(columns={
    'Lower_Salary': 'Min_Salary',
    'Upper_Salary': 'Max_Salary',
    'Avg_SalaryK': 'Avg_Salary',
    'spark': 'Spark',
    'aws': 'AWS',
    'excel': 'Excel',
    'sql_': 'SQL',
    'sas': 'SAS',
    'keras': 'Keras',
    'pytorch': 'PyTorch',
    'scikit': 'Scikit_Learn',
    'tensor': 'TensorFlow',
    'hadoop': 'Hadoop',
    'tableau': 'Tableau',
    'bi': 'Power_BI',
    'flink': 'Flink',
    'mongo': 'MongoDB',
    'google_an': 'Google_Analytics'
}, inplace=True)

In [68]:
df.head(21)

,Job_Title,Salary_Estimate,Company_Name,Location,Headquarters,Type_of_ownership,Industry,Sector,Revenue,Competitors,Hourly,Employer_provided,Min_Salary,Max_Salary,Avg_Salary,company_txt,Job_Location,Python,Spark,AWS,Excel,SQL,SAS,Keras,PyTorch,Scikit_Learn,TensorFlow,Hadoop,Tableau,Power_BI,Flink,MongoDB,Google_Analytics,Job_Category,Seniority_Title,Degree_Required,Company_Rating,State_Wise,Company_Man_Power,Company_Man_Power_Category,Founded_Year,Company_Age,Ownership_Type
0,data scientist,$53K-$91K (Glassdoor est.),Tecolote Research,"Albuquerque, NM","Goleta, CA",Company - Private,Aerospace & Defense,Aerospace & Defense,$50 to $100 million (USD),-1,0,0,53,91,72.0,Tecolote Research,NM,1,0,0,1,0,1,0,0,0,0,0,1,1,0,0,0,Data Scientist,Not Specified,Masters,3.8,NM,501 - 1000,Medium,1973,53,Private
1,healthcare data scientist,$63K-$112K (Glassdoor est.),University of Maryland Medical System,"Linthicum, MD","Baltimore, MD",Other Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1,0,0,63,112,87.5,University of Maryland Medical System,MD,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Data Scientist,Not Specified,Masters,3.4,MD,10000+,Very Large,1984,42,Other
2,data scientist,$80K-$90K (Glassdoor est.),KnowBe4,"Clearwater, FL","Clearwater, FL",Company - Private,Security Services,Business Services,$100 to $500 million (USD),-1,0,0,80,90,85.0,KnowBe4,FL,1,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,Data Scientist,Not Specified,Masters,4.8,FL,501 - 1000,Medium,2010,16,Private
3,data scientist,$56K-$97K (Glassdoor est.),PNNL,"Richland, WA","Richland, WA",Government,Energy,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa...",0,0,56,97,76.5,PNNL,WA,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Data Scientist,Not Specified,Not_Specified,3.8,WA,1001 - 5000,Large,1965,61,Government
4,data scientist,$86K-$143K (Glassdoor est.),Affinity Solutions,"New York, NY","New York, NY",Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee",0,0,86,143,114.5,Affinity Solutions,NY,1,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,Data Scientist,Not Specified,Not_Specified,2.9,NY,51 - 200,Small,1998,28,Private
5,data scientist,$71K-$119K (Glassdoor est.),CyrusOne,"Dallas, TX","Dallas, TX",Company - Public,Real Estate,Real Estate,$1 to $2 billion (USD),"Digital Realty, CoreSite, Equinix",0,0,71,119,95.0,CyrusOne,TX,1,0,1,1,1,0,0,0,0,0,0,0,1,0,1,0,Data Scientist,Not Specified,Not_Specified,3.4,TX,201 - 500,Medium,2000,26,Public
6,data scientist,$54K-$93K (Glassdoor est.),ClearOne Advantage,"Baltimore, MD","Baltimore, MD",Company - Private,Banks & Credit Unions,Finance,Unknown / Non-Applicable,-1,0,0,54,93,73.5,ClearOne Advantage,MD,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,Data Scientist,Not Specified,Not_Specified,4.1,MD,501 - 1000,Medium,2008,18,Private
7,data scientist,$86K-$142K (Glassdoor est.),Logic20/20,"San Jose, CA","Seattle, WA",Company - Private,Consulting,Business Services,$25 to $50 million (USD),-1,0,0,86,142,114.0,Logic20/20,CA,1,1,1,1,1,0,0,1,0,1,0,0,0,0,0,0,Data Scientist,Not Specified,Masters,3.8,CA,201 - 500,Medium,2005,21,Private
8,research scientist,$38K-$84K (Glassdoor est.),Rochester Regional Health,"Rochester, NY","Rochester, NY",Hospital,Health Care Services & Hospitals,Health Care,$500 million to $1 billion (USD),-1,0,0,38,84,61.0,Rochester Regional Health,NY,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Other Scientist,Not Specified,PhD,3.3,NY,10000+,Very Large,2014,12,Healthcare
9,data scientist,$120K-$160K (Glassdoor est.),<intent>,"New York, NY","New York, NY",Company - Private,Internet,Information Technology,$100 to $500 million (USD),"Clicktripz, SmarterTravel",0,0,120,160,140.0,<intent>,NY,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Data Scientist,Not Specified,Not_Specified,4.6,NY,51 - 200,Small,2009,17,Private
10,data scientist,$126K-$201K (Glassdoor est.),Wish,"San Jose, CA","San Francisco, CA",Company - Private,Other Retail Stores,Retail,$1 to $2 billion (USD),-1,0,0,126,201,163.5,Wish,CA,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Data Scientist,Not Specified,Not_Specified,3.5,CA,501 - 1000,Medium,2011,15,Private
11,data scientist,$64K-$106K (Glassdoor est.),ManTech,"Chantilly, VA","Herndon, VA",Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1,0,0,64,106,85.0,ManTech,VA,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,Data Scientist,Not Specified,Not_Specified,4.1,VA,5001 - 10000,Large,1968,58,Public
12,staff data scientist technology,$106K-$172K (Glassdoor est.),Walmart,"Plano, TX","Bentonville, AR",Company - Public,"Department, Clothing, & Shoe Stores",Retail,$10+ billion (USD),"Target, Costco Wholesale, Amazon",0,0,106,172,139.0,Walmart,TX,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,Data Scientist,Not Specified,Masters,3.2,TX,10000+,Very Large,1962,64,Public
13,data analyst,$46K-$85K (Glassdoor est.),Yesler,"Seattle, WA","Seattle, WA",Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,-1,0,0,46,85,65.5,Yesler,WA,1,1,1,1,1,0,0,0,0,0,0,1,1,0,0,0,Data Analyst,Not Specified,Not_Specified,4.1,WA,201 - 500,Medium,2012,14,Private
14,data scientist,$83K-$144K (Glassdoor est.),Takeda Pharmaceuticals,"Cambridge, MA","OSAKA, Japan",Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),"Novartis, Baxter, Pfizer",0,0,83,144,113.5,Takeda Pharmaceuticals,MA,1,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,Data Scientist,Not Specified,Masters,3.7,MA,10000+,Very Large,1781,245,Public
15,data engineer i,$102K-$190K (Glassdoor est.),Audible,"Newark, NJ","Newark, NJ",Subsidiary or Business Segment,Motion Picture Production & Distribution,Media,Unknown / Non-Applicable,-1,0,0,102,190,146.0,Audible,NJ,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,Data Engineer,Not Specified,Not_Specified,3.6,NJ,1001 - 5000,Large,1995,31,Subsidiary
16,scientist i ii biology,$67K-$137K (Glassdoor est.),Blueprint Medicines,"Cambridge, MA","Cambridge, MA",Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$1 to $5 million (USD),"bluebird bio, Agios Pharmaceuticals, Celgene",0,0,67,137,102.0,Blueprint Medicines,MA,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,Other Scientist,Not Specified,PhD,3.9,MA,51 - 200,Small,2011,15,Public
17,customer data scientist,$118K-$189K (Glassdoor est.),h2o.ai,"Mountain View, CA","Mountain View, CA",Company - Private,Enterprise Software & Network Solutions,Information Technology,Unknown / Non-Applicable,-1,0,0,118,189,153.5,h2o.ai,CA,1,1,1,1,0,0,0,0,0,0,1,0,0,0,0,0,Data Scientist,Not Specified,Masters,4.3,CA,201 - 500,Medium,2011,15,Private
18,data scientist health data analytics,$110K-$175K (Glassdoor est.),Nuna,"San Francisco, CA","San Francisco, CA",Company - Private,Enterprise Software & Network Solutions,Information Technology,Unknown / Non-Applicable,-1,0,0,110,175,142.5,Nuna,CA,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,Data Scientist,Not Specified,Not_Specified,4.2,CA,51 - 200,Small,2010,16,Private
19,data scientist,$64K-$111K (Glassdoor est.),Pinnacol Assurance,"Denver, CO","Denver, CO",Nonprofit Organization,Insurance Carriers,Insurance,$500 million to $1 billion (USD),-1,0,0,64,111,87.5,Pinnacol Assurance,CO,1,0,0,1,1,0,1,1,1,1,0,0,0,0,0,0,Data Scientist,Not Specified,Masters,4.0,CO,501 - 1000,Medium,1915,111,Nonprofit
20,data scientist,$81K-$130K (Glassdoor est.),Porch,"Seattle, WA","Seattle, WA",Company - Private,Internet,Information Technology,Unknown / Non-Applicable,"Angie's List, HomeAdvisor, Thumbtack",0,0,81,130,105.5,Porch,WA,1,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,Data Scientist,Not Specified,Masters,3.2,WA,201 - 500,Medium,2012,14,Private

In [69]:
df.drop(['Type_of_ownership'],axis=1, inplace=True)

In [70]:
# Save as CSV file on Desktop
df.to_csv(r'C:\Users\puspa\OneDrive\Desktop\Job_Market_ Analysis\Job_Market_Analysis_Final.csv', index=False)